export const Connection = [
  "¿Qué hay en el primer puesto de tu lista de deseos?",
  "¿Por qué estás más agradecido?",
  "¿Qué es lo que más lamentas en la vida?",
  "¿Qué es lo que más temes?",
  "¿Qué es lo que más te apasiona?",
  "¿Cómo te gusta pasar tu tiempo libre?",
  "¿Cómo sería tu día perfecto?",
  "¿Cómo es tu vida soñada?",
  "¿Qué es lo típico que puede arruinarte un día cualquiera?",
  "Si ganaras ahora mismo 10 millones de euros, ¿en qué lo invertirías?",
  "¿Cuál es tu pesadilla más recurrente?",
  "¿Alguna vez has soñado algo que luego se ha hecho realidad?",
  "¿Alguna vez has tenido una premonición?",
  "¿Qué te daba más miedo de pequeño?",
  "¿Qué enfermedad te da más miedo?",
  "¿Tienes esperanza en otra vida o sensación de trascendencia?",
  "¿Has tenido alguna experiencia que te da intuición de que exista otra vida?",
  "¿A qué personaje histórico admiras?",
  "¿Qué cambio en la sociedad crees que nos haría mejorar?",
  "¿Qué eventos de los que están pasando te da peor espina?",
  "¿Quién de tu familia te ha dado la lección de vida más bonita?",
  "Si tuvieras 10 millones de seguidores en Instagram, ¿de qué temas hablarías?",
  "¿Con qué causa estás especialmente concienciado?",
  "¿Qué injusticias te revuelven más el estómago?",
  "¿Y qué canción pedirías que sonara en tu última despedida?",
  "¿Qué es lo que la gente nunca adivinaría con solo mirarte?",
  "¿Qué es lo que más te hace reír?",
  "¿Has tomado alguna vez una decisión que haya cambiado tu vida?",
  "¿Cuál fue el día más feliz de tu vida?",
  "¿Qué es lo que más te gusta de ti?",
  "¿Qué decían los profesores sobre ti en tu boletín de notas y sigue siendo cierto?",
  "¿Qué es lo que te gustaría cambiar de ti mismo?",
  "¿De qué decisión de tu vida te arrepientes más?",
  "¿Te sientes identificado con el estereotipo de tu signo del zodiaco?",
  "¿Qué es lo que más te arrepientes de no haber hecho?",
  "¿Hay algo que no te atreviste a hacer en su día que ahora sí te sientes capaz?",
  "¿Qué rasgo de tu personalidad ha cambiado más con el tiempo?",
  "¿De qué cambio personal estás más orgulloso?",
  "¿Qué hiciste de joven que ahora no te atreverías ni de coña?",
  "¿Qué te aburre soberanamente?",
  "¿Qué canción no puedes escuchar sin llorar?",
  "¿Y cuál canción te pones para levantarte el ánimo?",
  "¿Cuál dirías que fue la época más complicada de tu vida?",
  "Si pudieras congelar tu vida a una edad concreta, ¿cuál sería?",
  "Si pudieras viajar en el tiempo, ¿irías a tu pasado o a tu futuro?",
  "¿Cuál fue la primera foto que colgaste en Instagram?",
  "¿Cuál fue la última foto que colgaste en Instagram?",
  "¿Cambiarías tu vida por la de alguien que conoces?",
  "¿Por qué famoso te intercambiarías durante 24 horas?",
  "¿Qué libro te ha cambiado la vida?",
  "¿Qué valores de la infancia conservas igual que entonces?",
  "¿Sobre qué temas importantes has cambiado más tu opinión?",
  "¿Tenías algún mote en el colegio?",
  "Si pudieras elegir a cualquier persona en el mundo, ¿a quién querrías invitar a cenar?",
  "¿Te gustaría ser famoso? ¿De qué manera?",
  "Antes de hacer una llamada, ¿practicas lo que vas a decir? ¿Por qué?",
  "¿Qué sería un día perfecto para ti?",
  "¿Cuándo fue la última vez que cantaste para ti? ¿Y cuándo le cantaste a otra persona por última vez?",
  "Si pudieras vivir hasta los 90 años y tener la mente o el cuerpo de una persona de 30 años durante los últimos 60 años de tu vida, ¿cuál elegirías?",
  "¿Tienes un presentimiento secreto sobre cómo morirás?",
  "Nombra tres cosas que aparentemente tengamos en común.",
  "¿Por qué estás más agradecido en la vida?",
  "Si pudieras cambiar algo sobre la forma en que te criaron, ¿qué sería?",
  "Cuenta la historia de tu vida en cuatro minutos.",
  "Si pudieras despertar mañana con una nueva cualidad o habilidad, ¿cuál sería?",
  "Si una bola de cristal pudiera decirte la verdad sobre ti, tu vida, el futuro o cualquier otra cosa, ¿qué querrías saber?",
  "¿Hay algo que hayas soñado hacer durante mucho tiempo? ¿Por qué no lo has hecho?",
  "¿Cuál es el mayor logro de tu vida?",
  "¿Qué es lo que más valoras en una amistad?",
  "¿Cuál es tu recuerdo más preciado?",
  "¿Cuál es tu recuerdo más terrible?",
  "Si supieras que vas a morir repentinamente en un año, ¿cambiarías algo sobre la forma en que ahora vives? ¿Por qué?",
  "¿Qué significa la amistad para ti?",
  "¿Qué papeles juegan el amor y el afecto en tu vida?",
  "Turnarse para decir cinco cualidades que tiene la otra persona.",
  "¿Qué tan cercana y afectuosa es tu familia? ¿Sientes que tu infancia fue más feliz que la de la mayoría de las personas?",
  "¿Qué opinas de la relación con tu madre?",
  "Tres declaraciones verdaderas con “ambos”. Por ejemplo, “ambos estamos en esta habitación sintiendo...”",
  "Completa esta frase: “Ojalá tuviera a alguien con quien pudiera compartir...”",
  "Si usted iba a convertirse en un amigo íntimo de su pareja, comparta lo que sería importante para que él/ella sepa.",
  "Si te fueras a convertir en un amigo cercano de la otra persona, ¿qué te parecería importante que supiera?",
  "Comparte un momento incómodo en tu vida.",
  "¿Cuándo lloraste por última vez delante de otra persona? ¿Y solo?",
  "Dile a la otra persona algo que te gusta de ella.",
  "¿Hay algo que sea demasiado serio como para bromear al respecto?",
  "Si murieras esta noche sin la oportunidad de comunicarte con alguien, ¿qué lamentarías no haber dicho? ¿Por qué no lo has dicho todavía?",
  "Tu casa y todo lo que tienes se incendia. Después de salvar a tus seres queridos y mascotas, solo tienes tiempo para entrar una última vez y salvar un objeto. ¿Qué sería? ¿Por qué?",
  "De todas las personas de tu familia, ¿qué muerte te parecería la más perturbadora? ¿Por qué?",
  "Comparte un problema personal y pídele consejos a la otra persona para poder manejarlo. Además, pídele que te diga cómo considera que te sientes sobre este problema.",

  "¿Qué es lo más embarazoso que tus padres te han pillado haciendo?",
  "¿Has sido cruel o malo con alguien en alguna ocasión?",
  "¿Qué cosa es la más extravagante que has hecho estando solo?",
  "¿Tienes algún miedo que no le hayas contado a nadie?",
  "¿Cuál es el mayor rechazo que has tenido en el amor?",
  "¿Hay algún secreto que no le hayas contado a tus padres?",
  "¿Cuál es la mentira más grande que has contado y no te han pillado?",
  "¿Te consideras una persona feliz?",
  "¿Qué es lo que más te gusta de tu persona?",
  "¿Qué es lo que menos te gusta de tu persona?",
  "Si pudieras borrar alguna experiencia negativa de tu vida, ¿cuál sería?",
  "¿Qué es lo más loco que has hecho por amor?",
  "¿Cuál es la última mentira que has contado?",
  "¿Cuál es tu límite en las relaciones íntimas?",
  "¿Qué cambiarías de tu vida si pudieras?",
  "Si pudieras pedir un deseo ahora mismo, ¿cuál sería?",
  "¿Te gustaría tener una experiencia íntima con alguien de tu mismo sexo?",
  "¿Qué es lo que más te excita?",
  "¿Has dado tu brazo a torcer?",
  "¿Has utilizado algún objeto para fines sexuales a pesar de no ser ese su objetivo?",
  "¿Tienes alguna fantasía sexual?",
  "¿Le has roto el corazón a alguien alguna vez?",
  "¿Me vas a llamar mañana?",
  "¿Has hecho el amor en algún lugar prohibido?",
  "¿Has sido infiel alguna vez?",
  "¿Qué te satisface más?",
  "¿Cuándo fue la última vez que mentiste?",
  "¿Alguna vez has estado con alguien para olvidar a otra persona?",
  "¿Tienes algún pretendiente ahora mismo?",
  "¿Alguna vez has discutido con la pareja de un amigo?",
  "¿Has jugado con los sentimientos de alguien alguna vez?",
  "¿Te sientes solo?",
  "¿Qué es lo más extravagante que has hecho?",
  "¿Sueles abordar a las personas que te gustan, o te puede la timidez?",
  "¿Cuánto tiempo duró la relación amorosa más breve que has tenido?",
  "¿Has pensado alguna vez en tener algo con la madre de un amigo?",
  "¿Tendrías un afer con alguno/a de tus primos/as?",
  "¿Has tenido un encuentro íntimo con alguien a a quien hayas conocido ese mismo día?",
  "¿Dejarías a tu pareja actual si a cambio ganaras un millón de dólares?",
  "¿Has conocido alguna vez a alguien a quien le perdonarías todos los fallos?",
  "¿Cuánto dinero ganas?",
  "¿Cuánto dinero tienes ahorrado en el banco?",
  "¿Crees que se puede viajar en el tiempo?",
  "¿Has estado alguna vez detenido o en el calabozo?",
  "¿Dormías con algún peluche cuando eras pequeño/a?",
  "¿A qué partido político votas?",
  "¿Eres feminista?",
  "¿Alguna vez has tenido un accidente con el coche?",
  "¿Te has vestido alguna vez con ropa de tu pareja?",
  "¿Cuál es el disfraz más ridículo que has llevado?",
  "¿Alguna vez has pensado en hacerte un tatuaje?",
  "¿Te tatuarías el nombre de tu pareja?",
  "¿Cuál es el momento en que has sentido más dolor físico en tu vida?",
  "¿Con qué artista querrías pasar una noche loca?",
  "Si tuvieras que elegir, ¿a quién salvarías de un incendio: a un hombre o a una familia de perros?",
  "¿Qué es lo que te frustró no poder decirle ala última persona que te decepciono?",
  "¿Si tuvieses que ocultar una de las partes de tu cuerpo que normalmente muestras públicamente, cuál sería?",
  "¿Alguna vez has discriminado a alguien?",
  "¿Qué característica física te haría no tener una cita con una persona?",
  "¿Alguna vez has reprimido las ganas de robar algo?",
  "¿Cuántos días seguidos has llegado a estar acostándote con alguien diferente cada día?",
  "¿Harías un striptease?",
  "¿Me dejas ver el historial de tu navegador de smartphone?",
  "¿Te gustaría probar el BDSM?",
  "¿Alguna vez te has enamorado de la pareja de un amigo?",
  "¿Alguna vez te has enamorado de la pareja de un familiar?",
  "¿Te parece que estoy en buena forma?",
  "¿Te has llegado a arrepentir de acostarte con alguien?",
  "¿En qué aspectos crees que eres mejor que los demás?",
  "¿Qué situaciones te hacen querer comportarte mal?",
  "¿Qué es lo primero que pensaste al verme?",
  "¿Qué es lo primero que pensaste al conocerme?",
  "¿Has estado alguna vez con una pareja que fuera mucho más alta o mucho más bajita que tú?",
  "¿Qué opinas sobre el velo islámico?",
  "¿Estás contento/a con tu vida sexual?",
  "¿Tienes alguna deuda con alguien?",
  "¿Qué es la última cosa que has buscado en Google?",
  "¿Cuál es tu youtuber favorito?",
  "¿Por qué crees que hay pobreza?",
  "¿Has tenido algún trabajo que odiaras profundamente?",
  "¿Qué cantante te da vergüenza reconocer que te gusta?",
  "¿Hay alguna palabra secreta que sólo uséis con tus amigos?",
  "¿Cómo fue tu peor experiencia sexual?",
  "¿Te has enganchado alguna vez a alguna serie de TV muy mala?",
  "¿Cuál crees que es tu Cociente Intelectual independientemente de lo que digan los test?",
  "¿Alguna vez has visto películas de contenido adulto con tu familia en otra habitación?",
  "¿Qué opinas del capitalismo?",
  "¿Cuántos años de trabajar sin parar crees que necesitarías para hacerte rico/a?",
  "¿Con qué persona no te atreverías a debatir de política?",
  "¿Crees que se debe poder votar de cualquier cosa?",
  "¿Cuántas personas crees que te odian en el mundo?",
  "¿Hay alguien que crea que eres muy poco inteligente?",
  "¿Qué línea jamás cruzarías para conquistar a alguien?",
  "¿Alguna vez has estado hasta muy tarde por la noche jugando a un videojuego?",
  "¿Alguna vez has viajado a otra provincia solo para tener sexo?",
  "¿Alguna vez has viajado a otra país solo para tener sexo?",
  "¿En qué cosas crees que te admiran los demás?",
  "¿Alguna vez te has arrepentido de no insultar a alguien?",
  "¿Das importancia al dinero de tus potenciales parejas?",
  "¿Cuánto tiempo estarías sin salir de una cama si te pagasen un dolar por cada minuto?",
  "¿Hay algún/a deportista por el que darías todo por pasar una noche?",
  "¿Has hecho algo ilegal en lo que llevamos de año?",
  "¿Alguna vez se te ha caído una copa al suelo en un restaurante o discoteca?",
  "¿Cuál es la habilidad que querrías poseer con todas tus fuerzas pero que nunca pudiste desarrollar?",
  "Si fueses un dinosaurio, ¿cuál te gustaría ser?",
  "¿Alguna vez te has sentido solo a pesar de tener gente alrededor?",
  "¿Has escrito alguna vez un poema a alguien a quien querías?",
  "¿Has causado algún desperfecto en la vía pública en alguna ocasión?",
  "¿Eres de esas personas que solo pueden ir al lavabo en su casa?",
  "¿Qué harías para protegerte de una invasión zombi?",
  "¿Consideras que tu mascota es \"uno más de la familia\"?",
  "¿Te gusta la pizza con piña?",
  "¿Has probado alguna vez los caracoles?",
  "¿Qué harías si mañana te tocase la lotería?",
  "Cuando estás triste, ¿te pones música triste?",
  "¿Has fantaseado con tener una noche loca con alguien de más de 50 años?",
  "¿Tienes algún prejuicio sobre las gentes de alguna región de tu país?",
  "¿Cuál es el regalo más feo que te han hecho?",
  "¿Alguna vez estabas haciendo un trabajo de la universidad y lo has perdido todo y has tenido que empezarlo de cero?",
  "¿Cuál es la vez en que has hecho más el ridículo?",
  "¿Qué cualidad mía valoras más?",
  "¿Cuál es la parte de tu cuerpo que menos te gusta?",
  "Si fueras jefe de una multinacional, ¿serías un jefe estricto y exigente o más bien relajado y amigable?",
  "De tu grupo de amigos, ¿quién es el más (o la más) irresponsable?",
  "¿Quién es la persona que más necesitas en tu vida ahora mismo?",
  "¿Consideras que tienes actitudes machistas?",
  "¿Cuál fue el último libro que leíste?",
  "¿Cuántas horas al día pasas navegando por internet?",
  "¿Cuál es el regalo más incómodo que te ha dado un/a antiguo/a novio/a?",
  "¿Cuál es el peor concierto al que has asistido?",
  "¿Cuál es el deporte que se te da peor?",
  "¿Alguna vez te has quedado sin gasolina? ¿Cómo resolviste la situación?",
  "¿Quieres más a tu padre o a tu madre?",
  "¿Te avergüenzas de algún gusto musical que tenías cuando eras adolescente?",
  "¿Has conocido alguna vez a algún famoso? ¿Qué pasó?",
  "¿Con el paso de los años, has cambiado de ideología?",
  "¿Cuál es el peor antro al que has ido?",
  "¿Has visto en alguna ocasión a una persona muerta?",
  "Si pudieras elegir, ¿dónde irías a vivir?",
  "¿Cuál es la asignatura que se te daba peor en la escuela?",
  "¿Te has caído alguna vez por la calle?",
  "¿Cuál es la pregunta incómoda que más detestas que te hagan?",
  "¿Alguna vez has reciclado un regalo que te hicieron a ti para regalarlo tú a otra persona?",
  "¿Prefieres tener medio millón de euros para gastar en 1 día o 300.000€ para gastar durante un mes?",
  "Si te tocara la lotería, ¿informarías a tus amigos?",
  "¿Alguien de tu familia tiene algún trastorno mental?",
  "¿Has roto algún mueble en alguna ocasión por ir borracho?",
  "¿Cuál era tu cómic favorito cuando eras niño/a?",
  "¿Si pudieras elegir una cualidad de entre estas tres, cuál te quedarías? Ser alto, ser guapo o ser exitoso.",
  "¿Has comido alguna vez algo que te hiciera vomitar (o casi)?",
  "¿Te has acostado alguna vez con alguien por un motivo que no fuera ni amor ni atracción?",
  "¿Qué personaje público consideras un mito erótico?",
  "¿Qué es más importante en tu vida: tu vida personal o tu carrera profesional?",
  "¿Sabes imitar la voz de algún famoso?",
  "Termina la frase: \"No podría vivir en una casa que no tuviera...\"",
  "¿Quién de tu grupo de amigos consideras que es menos confiable?",
  "¿Hasta qué edad te gustaría vivir?",
  "¿Crees en el derecho a llevar armas?",
  "¿A qué tipo de personas crees que jamás podrías seducir?",
  "¿Cuál es el talento que te frustra más no tener?",
  "¿Qué es lo más asqueroso que te ha pasado?",
  "¿A cuántos de tus amigos entregarías a la policía su supieses que han estado comentiendo crímenes?",
  "¿Alguna vez has consumido drogas solo para intentar flirtear con alguien?",
  "¿Alguna vez has intentado obtener mejores calificaciones haciendo trampas?",
  "¿Crees que hay áreas de conocimiento que jamás serías capaz de aprender?",
  "¿Te han rechazado un beso alguna vez?",
  "¿Has mentido alguna vez para ligar?",
  "¿Cuál es tu definición de “amor”?",
  "¿Has encontrado a alguien manteniendo relaciones sexuales?",
  "¿Crees en dios?",
  "¿Has tenido alguna pareja mucho mayor o más joven que tú?",
  "¿Qué opinión tienes sobre la eutanasia?",
  "¿Te gustaría ser millonario?",
  "¿Qué opinión tienes sobre el gobierno?",
  "¿Qué opinas sobre el comunismo?",
  "¿Saldrías con una actriz porno?",
  "¿A qué edad perdiste la virginidad?",
  "¿Qué es lo peor que has hecho para acostarte con alguien?",
  "¿Cuál es el peor insulto que has dedicado a alguien?",
  "¿Te has peleado alguna vez?",
  "¿Qué opinas del rey?",
  "¿Hasta qué edad te orinaste en la cama?",
  "¿Qué opinión tienes de la policía?",
  "¿Qué opinas de los judíos?",
  "¿Qué opinas de los asiáticos?",
  "¿Si volvieses a nacer, repetirás tu vida de la misma manera?",
  "¿Si pudieses elegir, en qué país te gustaría nacer?",
  "¿Crees que los pobres no se esfuerzan lo suficiente?",
  "¿Qué opinas de la infidelidad?",
  "¿Qué opinas del matrimonio?",
  "¿Qué opinas de la Iglesia?",
  "¿Qué opinas del aborto?",
  "¿Crees que todas las razas son igual de inteligentes?",
  "¿Qué opinas sobre la prostitución?",
  "¿Qué opinas sobre la cadena perpetua?",
  "¿Qué opinas sobre la inmigración?",
  "¿Crees que todo el mundo debería poder votar?",
  "¿Qué opinión te merecen los homosexuales?",
  "¿Qué opinas de Jeff Bezos?",
  "¿Qué opinión te merecen las políticas de identidad?",
  "¿Cuál es la comida que no puedes ni oler?",
  "¿Vivirías aislado en una cabaña durante 1 mes a cambio de 15.000€?",
  "Si solo pudieras comer un alimento por el resto de tu vida, ¿cuál sería?",
  "¿Cuál es la leyenda urbana que más tiempo has creído que era verdadera?",
  "¿Qué opinas de la nueva ley en España que hace que una persona pueda cambiar su sexo sin necesidad de pasar por pruebas médicas o psicológicas?",
  "¿Qué medio de transporte soportarías mejor en un viaje largo?",
  "¿Alguna vez has descargado alguna película para adultos en tu ordenador?",
  "¿Tienes alguna canción que te encanta a pesar de que los demás suelen considerarla una canción cutre?",
  "¿Alguna vez se te ha roto un teléfono móvil de forma graciosa o absurda?",
  "¿Alguna vez te han cacheado?",
  "Si pudieras escoger bañarte en una piscina llena de un líquido diferente al agua, ¿qué líquido pedirías?",
  "Si fueras testigo de una pelea en la calle, ¿serías capaz de intentar mediar o pasarías de largo?",
  "¿Qué opinas de la piratería de música y películas?",
  "¿Qué fruta no soportas?",
  "¿En qué situación temiste más por tu vida?",
  "¿Cuál es tu dibujo animado favorito?",
  "¿Has vomitado alguna vez en algún sitio público?",
  "¿A qué ciudad nunca irías a vivir?",
  "¿Qué es lo que más te molesta de mí?",
  "¿De qué color nunca irías vestido a una boda?",
  "¿Cuál es el famoso que más te ilusionaría encontrarte por la calle?",
  "¿Cuál es la apuesta más loca que has hecho en tu vida?",
  "¿Qué cosa quisiste aprender pero nunca lo lograste?",
  "¿Te has caído alguna vez cuando mucha gente te estaba mirando?",
  "¿Cuál es el trabajo que no harías ni aunque te pagaran un sueldo increíble?",
  "¿Alguna vez has salido de casa sin ropa interior o sin bañador?",
  "¿Qué juego basado en la agilidad mental se te da peor?",
  "¿Cuál fue la vez en la que fuiste más cruel con alguien que te estaba ofreciendo un servicio?",
  "¿Cuál es la persona más famosa con la que has intentado hablar por Internet?",
  "¿Qué es lo más vergonzoso que has enviado en el último mes por el sistema de mensajería que más usas en tu móvil?",
  "¿Qué parte de tu cuerpo crees que ha envejecido o madurado menos que el resto?",
  "¿Cuál fue la vez en la que más quedaste en evidencia al creer que sabías lo suficiente acerca de un tema?",
  "¿En alguna ocasión alguien intentó flirtear descaradamente contigo y tú no te diste cuenta?",
  "¿Cuál es la creencia religiosa que consideras más absurda a pesar de estar muy extendida?",
  "¿En algún momento has llegado a creer que estabas viviendo una experiencia paranormal?",
  "¿Alguna vez has amenazado a alguien?",
  "¿Te has tirado un pedo en público alguna vez y te han pillado?",
  "¿Cuál es la vez que más tiempo has estado sin ducharte?",
  "¿Tienes miedo a algo?",
  "¿Alguna vez te has caído yendo en bicicleta?",
  "¿Cuál fue tu experiencia laboral más desastrosa?",
  "¿Cuál es la comida que más te ha disgustado probar?",
  "¿Alguna vez se te ha caído el móvil al retrete?",
  "¿Te has saltado un semáforo en rojo en alguna ocasión?",
  "¿Qué es lo que más te gustaría tener en la vida y aún no tienes?",
  "¿Cuál fue tu sueño sexual más tórrido?",
  "¿Has soñado con algún amigo/amiga?",
  "¿Te han roto el corazón alguna vez?",
  "¿Has hecho el amor en un avión?",
  "¿Qué harías si fueras invisible?",
  "¿Si pudieras viajar a cualquier parte del mundo, dónde irías?",
  "¿Tienes algún piercing?",
  "¿Has estado involucrado en alguna pelea?",
  "¿Has tenido relaciones sexuales en un cine?",
  "¿Cuál fue tu peor borrachera?",
  "¿Si anduvieses desnudo por la calle te taparías la cara o los genitales?",
  "¿Alguna vez te enamoraste de tu profesor?",
  "¿Qué edad tenía la persona de mayor edad con la que te has acostado?",
  "¿Qué edad tenía la persona de menor edad con la que te has acostado?",
  "¿Cuál fue tu peor cita?",
  "¿Cuál fue tu mejor cita?",
  "¿Qué opinas sobre el anarquismo?",
  "¿Crees que hombres y mujeres pueden ser amigos?",
  "¿Cómo te gustan los hombres/las mujeres?",
  "¿De qué equipo de fútbol eres?",
  "¿Qué opinas sobre el estado de Israel?",
  "¿Alguna vez te has pegado en una discoteca o en un bar?",
  "¿Cómo fue tu primera experiencia sexual?",
  "¿Has probado los insectos?",
  "¿Has probado la comida de perro?",
  "¿De todos tus amigos, cuál es el que más bebe?",
  "¿Has sufrido algún coma etílico?",
  "¿Cuál fue tu primer mito erótico?",
  "¿Crees en el demonio?",
  "¿Has rechazado un beso alguna vez?",
  "¿Qué opinas de Estados Unidos?",
  "¿Qué opinas de los negros?",
  "¿Quieres casarte?",
  "¿Qué opinas del presidente de tu país?",
  "¿Crees en los extraterrestres?",
  "¿Dónde te gustaría vivir?",
  "¿En qué lugar transcurrirían tus vacaciones perfectas?",
  "¿Me puedes describir tu dormitorio?",
  "¿A qué personaje histórico te gustaría entrevistar?",
  "¿Qué tipo de ropa no llevarías puesta en ningún caso?",
  "¿Cuáles son tus tres bandas de música favoritas?",
  "¿Qué es para ti la libertad?",
  "¿Cuál es el aspecto sobre ti que más te gusta?",
  "¿Cuál es tu libro favorito?",
  "¿Sueles pensar a menudo sobre lo que te ocurre y lo que sientes?",
  "¿Qué superpoder tendrías?",
  "¿Qué cuatro series son tus favoritas?",
  "¿Qué tres cosas aprecias más en una persona?",
  "¿Cómo te gustaría ser en un futuro?",
  "¿Si fueses un animal, cuál serías?",
  "¿Qué canción serviría para resumir tu personalidad? ¿Por qué?",
  "¿Qué cuatro adjetivos te describen mejor?",
  "¿Cuál es el estado de ánimo que menos te gusta?",
  "¿Cómo te describirían tus amigos y amigas?",
  "¿Qué tres tipos de oficio te gustaría ejercer?",
  "¿Qué habilidad te gustaría perfeccionar para llegar a dominar totalmente?",
  "¿Si sólo pudieras conservar cinco números de teléfono de gente ajena a tu familia, cuáles serían?",
  "¿A qué tipo de persona le tendrías miedo?",
  "¿Qué es lo más alocado que has hecho?",
  "¿Cuál sería un buen título para tu autobiografía?",
  "¿Qué es lo que la mayoría de la gente suele pensar de ti y no es cierto?",
  "¿Qué te hubiera gustado empezar a aprender 5 años atrás?",
  "¿Qué tipo de personas te parecen especialmente atractivas?",
  "¿Qué características te gusta que estén presentes en otras personas pero no en ti?",
  "¿Sobre qué tema te gustaría que te preguntaran para conocerte mejor?",
  "¿Qué tipo de música te gusta bailar?",
  "¿Si vieses a un perro cuya pata ha quedado atrapada en una verja, ¿qué harías? ¿Y si en vez de un perro fuese un lagarto?",
  "¿En qué situaciones estarías dispuesto o dispuesta a mentir?",
  "¿A qué le tienes un mayor miedo irracional?",
  "¿De qué manera prefieres relacionarte con las personas?",
  "¿Cómo definirías tu tipo de sentido del humor?",
  "¿A qué sitio irías a relajarte durante unos días?",
  "Y... ¿A qué sitio irías a vivir una aventura?",
  "¿Cuál es el recuerdo de tu infancia que tienes más vivo?",
  "¿Cuándo te diste cuenta de que habías entrado en la adultez?",
  "¿Qué es lo que echas más de menos de tu infancia?",
  "¿Qué clase de personas son las que te dan más lástima?",
  "¿Con qué tipo de personas te daría vergüenza que te vieran?",
  "¿Qué 3 personas son las que más te inspiran?",
  "¿Te consideras una persona supersticiosa?",
  "¿Prefieres las historias cortas y simples o los argumentos enrevesados y complejos?",
  "¿Te gusta saber lo que está pasando en lugres lejanos, o solo te interesa lo local?",
  "¿Con qué personaje de ficción te identificas más?",
  "¿De qué miembros de tu familia has aprendido más?",
  "¿Qué miembro de tu familia es un mayor ejemplo para ti?",
  "¿Tienes claro lo que buscas en la vida?",
  "¿Con qué tipo de personas jamás te llevarías bien?",
  "¿Con qué clase de persona te negarías a hablar?",
  "¿Cuánto tiempo ha pasado desde que ocurrió algo de lo que te arrepientes profundamente?",
  "¿Te haría sentir mal irte llevándote contigo muchos secretos?",
  "¿Crees que eres una persona abierta a los cambios?",
  "¿Te sientes amenazado o amenazada fácilmente?",
  "¿Crees que la reputación es algo importante, para ti?",
  "¿Es mejor defender causas por su legitimidad, o por la posibilidad de llevarlas a la práctica?",
  "¿Te cuesta hablar sobre ti?",
  "¿Cuál ha sido la mascota a la que has querido más?",
  "¿Cuándo fue que gastaste más dinero en algo totalmente prescindible?",
  "Si no trabajaras en lo que trabajas actualmente, ¿a qué te hubiera gustado dedicarte?",
  "¿Cuál es el primer recuerdo que tienes en tu vida?",
  "¿Quién es tu referente en la vida?",
  "¿Con qué dinero en el banco crees que decidirías retirarte?",
  "¿Qué juguete de tu infancia te hizo más ilusión?",
  "¿En qué época histórica te gustaría vivir si volvieras a nacer?",
  "¿Cuál es tu juego de mesa favorito?",
  "¿Prefieres ser el jefe o recibir órdenes y ejecutarlas?",
  "¿Cuál crees que es el peor delito que has cometido en tu vida?",
  "¿Cuál es tu rasgo de personalidad del cual te sientes más orgulloso/a?",
  "¿Qué color crees que te define mejor?",
  "¿Cuál crees que sería un regalo perfecto para mí?",
  "¿Cuál es el deporte que se te da peor?",
  "¿En qué temas crees que sabes más que el 95% de la gente?",
  "Si fueses una persona millonaria y te propusieras crear una ONG de protección de la naturaleza, ¿a qué especie animal la dedicarías?",
  "¿En qué videojuego vivirías?",
  "¿Y en qué película vivirías?",
  "¿Crees que es posible copiar en el mundo del arte?",
  "¿Te gustaría estudiar algo cuando te jubiles?",
  "¿Si pudieras tener un jardín enorme, ¿cuáles son las principales plantas que pondrías?",
  "¿Te gusta disfrazarte?",
  "¿Hay alguna cultura a la que admires?",
  "Si te propusieras escribir una novela de fantasía, ¿crearías tu propio mundo mágico totalmente nuevo partiendo desde cero o tratarías de imitar otro que ya ha creado otro autor?",
  "¿Qué crees que te hace falta para ser mejor persona?",
  "¿Qué animal carnívoro te daría más miedo encontrarte paseando por un bosque?",
  "¿Cuál es la ocasión en el que has hecho más el ridículo ante los demás?",
  "¿Y cuál es la ocasión en el que has hecho más el ridículo ante ti mismo/a, sin que te viera nadie?",
  "¿Qué es lo que más te interesa saber de mí?",
  "¿Si pudieras repetir una experiencia o momento de tu vida, cuál elegirías?",
  "¿Qué crees que es lo que piensan de ti la primera vez que te ven?",
  "¿Cuál es tu día favorito del año?",
  "¿Qué continente consideras que tiene una Historia más interesante?",
  "¿A qué profesor o profesora de tu infancia les estás más agradecido/a?",
  "¿Qué opinas sobre la idea de prohibir las drogas?",
  "¿A qué planeta te gustaría más viajar?",
  "¿A qué persona famosa viva actualmente te gustaría conocer?",
  "¿Y a qué persona famosa que ya no está viva te gustaría conocer?",
  "¿Temes envejecer?",
  "¿Cuál es la parte de tu cuerpo que más te gusta?",
  "¿Quién es tu director de cine favorito?",
  "¿Crees que sería posible viajar en el tiempo?",
  "¿Cuál es la persona adulta que no es de tu familia que más te marcó durante tu infancia?",
  "Si solo pudieras comer un único plato durante el resto de tu vida, ¿cuál sería?",
  "¿Cuál es tu humorista favorito/a?",
  "¿Cuáles son los temas sobres los que más te gusta debatir?",
  "¿En qué momento de tu vida fuiste más feliz?",
  "¿Qué famoso te cae peor?",
  "Si fueras famoso, ¿te gustaría que te parasen por la calle para pedirte fotos, o lo odiarías?",
  "Si te vieses forzado a ir a la guerra y solo pudieras llevar un arma, ¿cuál sería?",
  "¿Qué animal te da más repelús?",
  "¿Sufres alguna alergia?",
  "¿Cuál fue el momento más duro de tu vida y por qué?",
  "¿Quién es tu mejor amigo/a?",
  "¿Cuál es el 'look' más extremo que has llevado en tu vida?",
  "¿Llevas algún tatuaje? ¿Qué significa?",
  "¿Hay alguna causa que defiendas a capa y espada?",
  "¿Crees que en 5 años serás una persona rica?",
  "¿Cuál es la peor lesión que has sufrido?",
  "¿Te someterías a alguna operación de cirugía estética?",
  "¿Cuál es la playa más bonita en la que has estado?",
  "¿Qué cambiarías de mi personalidad?",
  "¿Qué es lo que te hace más feliz en tu día a día?",
  "¿Cuál es el libro que más te ha marcado?",
  "¿Tienes algún secreto que no me hayas contado?",
  "Dime tres bandas musicales que te hayan marcado",
  "¿Qué te da miedo?",
  "¿Dónde te irías de vacaciones?",
  "¿Cuál sería tu trabajo soñado?",
  "Si pudieras entrevistar a alguien, ¿quién sería?",
  "¿Tienes algún libro favorito? ¿Cuál es?",
  "¿Qué es lo que más valoras de nuestra amistad?",
  "¿Qué significado tiene para ti la libertad?",
  "¿Con qué personaje histórico te gustaría cenar?",
  "Si dominaras el mundo, ¿qué harías para cambiarlo?",
  "¿Qué superpoder tendrías si pudieras elegir?",
  "¿Hay alguna prenda de ropa que no te pondrías nunca?",
  "¿Piensas con frecuencia en cómo te sientes?",
  "Dime cuatro series que más te gusten",
  "¿Qué cualidades valoras más en alguien?",
  "¿Cómo ves el futuro?",
  "¿Mar o montaña?",
  "¿Cómo es tu dormitorio?",
  "¿Qué comerías en tu última cena?",
  "¿Te identificas con alguna canción?",
  "¿Cuál es el recuerdo más vergonzoso de tu infancia?",
  "¿Cuál es el estado de ánimo más desagradable para ti?",
  "¿Cuál es tu película favorita? ¿Por qué?",
  "¿Cómo me describirías?",
  "¿Tienes algún modelo a seguir?",
  "Cuando eras pequeño, ¿qué querías ser de mayor?",
  "¿Qué es lo que más deseas en este mundo?",
  "¿Tienes un sitio preferido para vivir?",
  "¿Hay algo que pienses que los demás piensan de ti y no es cierto?",
  "Si te hicieras un tatuaje, ¿de qué se trataría?",
  "¿Qué tipo de música te gusta más?",
  "¿Qué clase de personas son las que te dan más lástima?",
  "Si fueses un animal… ¿cuál serías?",
  "¿Quién es la persona más importante de tu vida?",
  "¿Qué es lo que echas más de menos de tu infancia?",
  "¿Qué es lo más extraño que has hecho en una cita?",
  "¿Perdonarías una infidelidad?",
  "¿Cuál ha sido tu mejor momento de tu vida?",
  "¿Con qué personaje de ficción te identificas más?",
  "¿A qué sitio irías a vivir una aventura?",
  "¿Quién te ha influenciado más en esta vida?",
  "¿Cuándo te percataste de que ya eras adulto?",
  "¿Dónde te irías conmigo a pasar unos días?",
  "¿Con qué tipo de personas te daría vergüenza que te vieran?",
  "Qué cuatro adjetivos te dicen cómo eres?",
  "¿Qué te gustaría lograr en esta vida?",
  "¿Eres una persona supersticiosa?",
  "¿Te gusta saber lo que está pasando en otros países?",
  "¿Qué es lo que más te gusta sobre tu persona?",
  "Si tuvieras que estar en un reality show, ¿de qué tendría que tratar?",
  "¿Qué tipo de personas son más atractivas para ti?",
  "¿Qué es para ti la infidelidad?",
  "¿En qué situaciones estarías dispuesto o dispuesta a mentir?",
  "Cómo definirías tu tipo de sentido del humor?",
  "¿Qué talento desearía tener?",
  "¿A qué sitio irías a relajarte durante unos días?",
  "¿De qué estás más orgulloso en esta vida?",
  "Y… ¿de lo que más te arrepientes?",
  "¿Cuál es tu mayor virtud y tu mayor defecto?",
  "¿Qué te frustra más no haber conseguido?",
  "¿Cómo lidias con la ansiedad?",
  "¿Con qué tipo de personas sientes más inseguridad o timidez?",
  "¿Hasta qué punto llegarías por conseguir fama?",
  "¿Crees que las amistades son para siempre?",
  "¿Te has declarado alguna vez?",
  "¿Contratarías a un amigo en tu empresa?",
  "¿Cuál es el amigo al que más confiarías un trabajo que implicara fuerza bruta?",
  "¿Se puede confiar en un amigo que nunca te propone hacer planes juntos?",
  "¿Cuál es el amigo que tiene más probabilidades de quedar inconsciente en una noche de fiesta?",
  "¿Cuál de tus amigos ha estado detenido por la policía en más ocasiones?",
  "¿Cuáles son, para ti, los tres valores más importantes?",
  "¿Preferirías tener un gran talento innato para una actividad, o la capacidad para poder esforzarte mucho?",
  "¿Cuál crees que es el adjetivo que mejor te define?",
  "¿En qué ámbito de tu vida opinas que se plasma más tu lado creativo?",
  "¿Cómo sería una sociedad gobernada por ti?",
  "¿Qué es para ti el amor?",
  "¿Cuál es tu principal miedo irracional?",
  "¿A qué edad crees que empezaste a ser una persona madura?",
  "¿Cómo te gustaría que te recuerden cuando ya no estés?",
  "¿Con qué superhéroe te identificas más?",
  "¿Prefieres los días lluviosos o soleados?",
  "¿Tienes alguna peca oculta en alguna parte de tu cuerpo?",
  "¿Cuál es el momento en que has estado más cerca de la muerte?"
]
