export const FireStarter = [
  "Si pudieras elegir el sexo y la apariencia física de tu bebé, ¿lo harías?",
  "¿Estarías dispuesto a tener pesadillas horribles durante un año si fuera recompensado con una riqueza extraordinaria?",
  "Durante un viaje a otra ciudad, tu pareja/amante conoce un atractivo extraño y pasan la noche juntos.Ya que nunca se volverán a encontrar, y tú nunca podrías enterarte del incidente, ¿querrías que tu pareja te lo contara?",
  "¿Alguna vez te ha gustado la pareja de un amigo o amiga?",
  "De todas las personas a las que conocemos, ¿con quién preferirías besarte?",
  "¿Quién crees que es la persona peor vestida del grupo?",
  "¿A quién salvarías primero de este grupo?",
  "¿Qué cambiarías de tu físico?",
  "¿Cuándo fue tu primer beso y con quién?",
  "¿Qué es lo mejor que has hecho en la cama?",
  "¿Y lo peor?",
  "¿Cuál es la mentira más grande que has contado?",
  "¿Alguna vez te has acostado con alguien y te has arrepentido?",
  "¿Alguna vez te has enamorado de la pareja de algún amigo?",
  "¿Cuál es el sitio más extraño en el que has tenido sexo?",
  "¿Quién fue tu primer gran 'crush'?",
  "¿Cuál ha sido la peor cita de tu vida?",
  "¿Cuál es tu mayor deseo?",
  "¿Qué es lo último que has buscado en el móvil?",
  "¿Y tu última foto guardada?",
  "¿Y el último mensaje que has enviado?",
  "¿Alguna vez has mandado 'nudes'?",
  "¿Alguna vez te has saltado la ley?",
  "¿Qué es lo más atrevido que has hecho nunca?",
  "¿Alguna vez te han puesto una multa?",
  "¿Has consumido drogas alguna vez?",
  "¿Te han arrestado alguna vez?",
  "¿Alguna vez has tenido piojos?",
  "¿Alguna vez has dudado sobre tu sexualidad?",
  "¿Alguna vez has fingido un orgasmo?",
  "¿Crees que tus amigos te conocen de verdad",
  "¿Crees que tu familia te conoce de verdad?",
  "¿Harías un 'striptease'?",
  "¿Cuál ha sido el mayor periodo de tiempo que has estado sin tener sexo?",
  "¿Cuál es el número máximo de personas con las que te has besado en una sola noche?",
  "¿Con qué título de película definirías tu vida?",
  "¿Cuál es la peor locura que has hecho por amor?",
  "¿Cuál es tu mayor arrepentimiento?",
  "Si pudieras hacer que alguien desapareciera para siempre, ¿quién sería?",
  "Si fueras invisible por un día, ¿qué harías?",
  "¿Te consideras exitoso en la vida?",
  "¿Crees que el amor puede durar para siempre?",
  "¿Alguna vez has sido infiel?",
  "¿Serías infiel a tu pareja por 1 millón de euros?",
  "¿Perdonarías una infidelidad?",
  "¿Qué es lo más raro que has hecho frente al espejo?",
  "¿Alguna vez has pillado a tus amigos haciéndolo?",
  "¿Y a tus padres?",
  "¿Alguna vez te has enamorado de quien no deberías?",
  "¿Alguna vez has mentido al decir te quiero?",
  "¿Tendrías una relación abierta?",
  "¿Cuál es tu fantasía sexual?",
  "¿Con quién harías un trio?",
  "¿Has hecho llorar a alguien alguna vez?",
  "¿Por qué es lo último por lo que has llorado?",
  "¿Te han dejado plantado alguna vez?",
  "¿Has dejado plantado a alguien alguna vez?",
  "¿Con quién te irías a vivir de nuestro grupo de amigos?",
  "¿Cuándo fue la última vez que lloraste y por qué?",
  "¿Alguna vez has tenido celos de algún amigo?",
  "¿Cuánto ha sido el máximo de tiempo que has estado sin ducharte?",
  "¿Cuánto dinero tienes en tu cuenta bancaria?",
  "¿Qué es lo primero que harías si te despertaras siendo del sexo opuesto?",
  "¿Qué es lo más patético que has hecho?",
  "¿Qué es lo más asqueroso que has hecho?",
  "¿Besarías a tu mejor amigo durante un minuto por 100 euros?",
  "¿Qué es lo último que te has comprado?",
  "¿Con qué famoso tendrías una relación?",
  "¿Alguna vez has intentado hablar con alguien famoso?",
  "¿Te gustaría ser famoso?",
  "¿Alguna vez has hecho pis en una piscina?",
  "¿Alguna vez has hecho pis en la ducha?",
  "¿Cantas en la ducha?",
  "¿Has copiado alguna vez en un examen?",
  "¿De qué color es tu ropa interior?",
  "¿Alguna vez has salido a la calle sin ropa interior?",
  "¿Cuál fue tu peor borrachera?",
  "¿Qué es lo peor que has hecho estando borracho?",
  "¿Cuál es el peor regalo que te han hecho?",
  "¿Has tenido sexo en público alguna vez?",
  "¿A qué momento volverías de tu pasado?",
  "¿Qué no volverías a hacer nunca más?",
  "¿Cuándo has pasado más miedo en tu vida?",
  "¿Cuándo has pasado más vergüenza en tu vida?",
  "¿Alguna vez te has comido un moco?",
  "¿Pegarías a un niño a cambio de un millón de euros?",
  "¿Alguna vez te has reído en el momento más inoportuno?",
  "¿Qué cantante te da vergüenza admitir que te gusta?",
  "¿Miras porno?",
  "¿Te gusta la pizza con piña?",
  "¿Quieres más a tu padre o a tu madre?",
  "¿Te depilas tus partes íntimas?",
  "¿Cuál es tu postura sexual favorita?",
  "¿Cada cuánto vas al baño?",
  "¿En qué piensas cuando estás en el váter?",
  "¿A quién matarías si supieras que nadie lo descubriría jamás?",
  "¿Dirías que tuviste una infancia feliz?",
  "¿Alguna vez te han roto el corazón?",
  "¿Alguna vez le has roto el corazón a alguien?",
  "¿Qué nota te darías en la cama?",
  "¿Usas juguetes sexuales?",
  "¿Cuándo fue la última vez que te rechazaron?",
  "¿Cuál es tu zona erógena más sensible?",
  "¿Eres virgen?",
  "¿Cuánto ganas al mes?",
  "¿Cuál ha sido tu mayor fracaso?",
  "¿Qué es lo más embarazoso que tus padres te han pillado haciendo?",
  "¿Cuál es la mentira más grande que has contado?",
  "¿Qué es lo más loco que has hecho en nombre del amor?",
  "¿Cuál es tu fantasía sexual que nunca has confesado?",
  "¿Has sido infiel?",
  "¿Te gusta alguien ahora mismo?",
  "¿Tendrías sexo con un primo o prima?",
  "¿Pegarías a un niño a cambio de un millón de euros?",
  "¿Cuánto dinero tienes en el banco?",
  "¿A quién votas?",
  "¿Qué es lo primero que pensaste al verme?",
  "¿Qué opinas del velo islámico?",
  "¿Qué es lo último que has buscado en Google?",
  "¿Qué cantante te da vergüenza admitir que te gusta?",
  "¿Cuál ha sido tu peor experiencia sexual?",
  "¿Cuántas veces te masturbas al día?",
  "¿Con cuántos años perdiste la virginidad?",
  "¿Miras porno?",
  "¿Has hecho algo ilegal? ¿El qué?",
  "¿Te sientes solo/a?",
  "¿Qué opinas del aborto?",
  "¿Qué opinas de la eutanasia?",
  "¿Qué opinas de la inmigración ilegal?",
  "¿Te gusta la pizza con piña?",
  "¿Cuál ha sido la vez que has hecho más el ridículo?",
  "¿Cuál es la parte de tu cuerpo que te gusta menos?",
  "¿Y la que te gusta más?",
  "¿Con cuál de tus amigos/as tendrías una noche de sexo?",
  "¿Quieres más a tu padre o a tu madre?",
  "¿Qué es lo peor que has hecho estando borracho?",
  "¿Podrías matar a alguien?",
  "¿Has consumido drogas alguna vez?",
  "¿Te han arrestado alguna vez?",
  "¿Has copiado en algún examen?",
  "¿Has mentido para ligar?",
  "¿Crees en Dios?",
  "¿Saldrías con una actriz (o actor) porno?",
  "¿Te has grabado alguna vez teniendo sexo?",
  "¿Qué opinas de la monarquía?",
  "¿Eres de derechas o de izquierdas?",
  "¿Tendrías una relación abierta?",
  "¿Qué opinas del matrimonio?",
  "¿Qué opinas de la pena de muerte?",
  "¿A quién odias?",
  "¿Cuándo fue la última vez que lloraste?",
  "¿Has robado?",
  "¿Tuviste una infancia feliz?",
  "¿Te han roto el corazón?",
  "¿Te has enamorado de la pareja de algún amigo?",
  "¿Perdonarías una infidelidad?",
  "¿Qué hay después de la muerte?",
  "¿Cantas en la ducha?",
  "¿Puedo ver tus conversaciones en Instagram?",
  "¿Con qué dos personas de tu entorno harías un trío?",
  "¿Has tenido que tomar la pastilla del día después?",
  "¿Con qué edad quieres tener hijos?",
  "¿Te depilas tus partes íntimas?",
  "¿Tus padres te han pillado teniendo sexo?",
  "¿Has enviado fotos desnudo/a alguna vez?",
  "¿El tamaño importa?",
  "¿Te has comido los mocos de otra persona alguna vez?",
  "¿Cuál es el objeto más raro que has usado como juguete sexual?",
  "¿Cómo fue tu primer beso?",
  "¿Cuál es tu posición sexual favorita?",
  "¿Qué harías si por un día pudieras ser del sexo opuesto?",
  "¿Cómo fue tu peor cita?",
  "¿Cada cuánto vas al baño?",
  "¿Qué parte de tu cuerpo te gusta más?",
  "¿Qué piensas de hacer un trío?",
  "¿Cómo te sentirías si pillas a tu pareja dándose autoplacer?",
  "¿Qué tipo de vacaciones preferirías con tu pareja, la montaña, la playa, una zona con ocio nocturno...?",
  "¿De qué te disfrazarías como fantasía sexual?",
  "¿Has utilizado alimentos afrodisíacos adrede?",
  "Si ves accidentalmente una una persona del sexo opuesto desnuda y no lo sabe, ¿seguirías mirando?",
  "¿Te resulta excitante acariciar a tu pareja sin tocarla con las manos?",
  "¿Qué prefieres, una cara bonita o un cuerpo sexy?",
  "Cuando algo no te apetece, ¿sabes poner límites?",
  "¿Has puesto a prueba tus fantasías más íntimas?",
  "Antes de que empezáramos a salir, ¿alguna vez fantaseaste conmigo?",
  "¿Qué crees que debería ser nuestro siguiente paso para hacer que nuestra vida sexual más emocionante?",
  "Te gusta practicar las relaciones íntimas en lugares poco habituales?",
  "¿Buscarías ayuda para corregir algún problema sexual?",
  "¿Qué es lo más importante para ti en la cama?",
  "¿Has descubierto los gustos sexuales de tu pareja?",
  "¿Qué tres cosas que te excitan?",
  "¿Has hecho llorar a alguna vez a alguien?",
  "¿Has probado el sexo tántrico?",
  "¿Tendrías sexo con alguien que acabas de conocer una noche?",
  "¿Buscas maneras de evitar la monotonía en la cama?",
  "¿Harías cibersexo?",
  "Cuéntame el sueño más sexy que jamás hayas tenido acerca de mí",
  "¿Le harías un striptease a tu pareja?",
  "¿Qué crees que es la parte más sexy de mi cuerpo?",
  "¿Cuál ha sido la cosa más “loca” que ha hecho por otra persona?",
  "¿ Haces trabajar tu creatividad cuando las circunstancias parecen poco favorables (hay gente cerca, hay poco tiempo, etc.)?",
  "¿Exploras tu cuerpo para descubrir tus zonas erógenas?",
  "¿Tomas suplementos para mantener tu líbido en forma?",
  "A pesar del ritmo de vida ajetreado, ¿sabes encontrar un momento para el placer sexual, aunque sea uno “rapidito\"?",
  "¿Disfrutas de las películas para adultos?",
  "¿Te atreves a mostrar tu deseo sexual y a tomar la iniciativa?",
  "¿Te gusta desnudarte delante de tu pareja, independientemente del estado de tu cuerpo?",
  "¿Con el tiempo has ido adquiriendo habilidades y destrezas que te permitan disfrutar más y mejor a ti y a tu pareja?",
  "¿Alguna vez has preparado un baño sensual para ti y tu pareja?",
  "¿Has probado a vendar vuestros ojos (el tuyo y el de tu pareja) para poner a prueba el resto de los sentidos?",
  "¿Usas el sentido del humor para hacer frente a algún contratiempo?",
  "¿Has leído algún libro de sexualidad para mejorar tu rendimiento o comprender mejor al sexo opuesto?",
  "¿Has recurrido al hielo para hacer más intensa la experiencia sexual?",
  "¿Qué es lo que más te gusta que te hagan en la cama?",
  "¿Has tenido alguna muy mala experiencia sexual?",
  "¿Practicas ejercicios para mejorar tu rendimiento sexual?",
  "¿Practicas el sexo más allá del coito o del orgasmo?",
  "¿Qué adjetivos te definen mejor respecto al sexo?",
  "¿Es bueno probar cosas diferentes en las relaciones íntimas?",
  "Del 1 al 10… ¿cuánta importancia le das al sexo en tus relaciones de pareja?",
  "¿Qué es lo que más te gusta hacer en la cama?",
  "¿Conoces la diferencia entre infidelidad y promiscuidad?",
  "¿Te esfuerzas por averiguar las zonas erógenas de tu pareja?",
  "¿Alguna vez has espiado a una pareja mientras tenían relaciones?",
  "¿Cuál es tu actor/actriz de cine erótico favorito/a?",
  "¿Cuántas veces calculas que has vomitado en tu vida por culpa de haber bebido demasiado?",
  "¿Has sentido atracción hacia algún profesor/a en tu etapa universitaria?",
  "¿Te consideras una persona tradicional o atrevida?",
  "¿Has tenido éxito al usar apps de ligoteo?",
  "¿Qué parte de tu cuerpo te gusta menos?",
  "¿En qué parte de tu cuerpo te someterías a operaciones de cirujía estética?",
  "¿Cuáles son los lugares más raros en los que has mantenido relaciones sexuales?",
  "¿Te has sentido atraído alguna vez por un amigo o amiga?",
  "¿Qué es lo primero en lo que te fijas del cuerpo de un hombre o de una mujer?",
  "¿Has fantaseado alguna vez con alguna celebridad?",
  "¿A qué edad perdiste la virginidad?",
  "¿Cómo sería tu cita ideal?",
  "¿Cuál ha sido tu mejor cita?",
  "¿Cuál ha sido tu peor cita?",
  "¿Has descubierto a tus padres manteniendo relaciones alguna vez?",
  "¿Has fantaseado alguna vez con personas del sexo opuesto?",
  "¿Te han descubierto alguna vez manteniendo relaciones íntimas?",
  "¿Con cuántas personas te has acostado?",
  "¿Has utilizado alguna vez juguetes eróticos?",
  "¿Has tenido alguna vez un “gatillazo”?",
  "¿Consumes pornografía habitualmente?",
  "¿Has grabado alguna vez un vídeo de contenido íntimo con tu pareja?",
  "¿Alguna vez has encontrado a un conocido o conocida en una app para ligar?",
  "¿Cuál es tu postura sexual favorita?",
  "¿Has tenido un sueño erótico con un amigo o amiga sin desearlo?",
  "¿Te consideras un experto en materia sexual?",
  "¿Cuándo fue la vez que más bebiste?",
  "¿Qué ha sido lo más atrevido que has hecho bebiendo de fiesta?",
  "¿Has ido a alguna playa nudista?",
  "¿Has tenido alguna enfermedad de transmisión sexual?",
  "¿Has sido infiel a tu pareja?",
  "¿Te has besado con más de una persona en una noche?",
  "¿Te has acostado con el ex de algún amigo?",
  "¿En qué país nunca querrías vivir?",
  "¿Con qué personaje famoso querrías tener una cita romántica?",
  "¿Qué youtuber consideras más sexy?",
  "¿Qué manía de higiene personal no puedes descuidar antes de un encuentro íntimo?",
  "¿Hay alguna profesión que no aceptarías en tu pareja?",
  "¿Qué comida evitarías a toda costa antes de una cita con alguien a quien estás conociendo?",
  "¿Te gusta que te aten?",
  "Por lo que me conoces... ¿Qué es lo que te gusta más de mi personalidad?",
  "¿Serías capaz de mantener una relación sexual con una persona desconocida mirando?",
  "¿Serías capaz de mantener una relación sexual con toda una audiencia mirando?",
  "¿Qué es lo que más te gusta que te digan durante el sexo?",
  "¿Qué opinas sobre el intercambio de parejas?",
  "¿Descartarías hacer una película erótica conmigo?",
  "¿Cuál crees que es el máximo de personas con las que te podrías acostar a la vez y llegar a disfrutarlo?",
  "¿Qué persona famosa crees que está más subestimada en cuanto a su atractivo físico?",
  "¿Qué es lo más ridículo que has llegado a hacer para flirtear?",
  "¿Conoces a alguien que te saque de tus casillas?",
  "¿Has llegado a lesionarte mientras mantenías relaciones?",
  "¿Qué proposición íntima sería una \"red flag\" y haría que no siguieras conociendo a esa persona?",
  "¿Las relaciones, con luz o sin luz?",
  "¿Cuál es tu fetiche más inconfesable?",
  "¿Para ti es más importante el amor o el sexo?",
  "¿Qué cantante querrías conocer en una cita romántica?",
  "¿Has fantaseado conmigo en alguna ocasión?",
  "¿Lo has hecho alguna vez dentro de un coche?",
  "¿Has usado lubricante alguna vez?",
  "¿Alguna vez has tenido un 'gatillazo'?",
  "¿Qué es lo te hace sentir vivo?",
  "¿Cuál es tu mayor miedo?",
  "¿Qué cambiarías de tí mismo?",
  "¿Cuál es tu mayor sueño?",
  "¿Alguna vez has sido cruel o has utilizado a alguien?",
  "¿Tienes algún vicio inconfesable?",
  "¿Cuando mentiste por última vez en algo importante?",
  "¿Qué es lo más vergonzoso que alguien te ha pillado haciendo?",
  "¿Qué piensas de ti mismo como persona?",
  "¿Tienes algún complejo? ¿Cuál?",
  "¿A quién de los otros candidatos no cogería y por qué?",
  "¿Cuál es la parte de tu cuerpo que más te gusta?",
  "¿Y del mío?",
  "¿De qué te arrepientes más?",
  "¿Hasta donde llegarías por cumplir un antojo?",
  "¿Qué es lo más loco que has hecho por amor?",
  "¿Prefieres ser el autor de una injusticia o su víctima?",
  "¿Te has rendido en algo en la vida?",
  "¿Alguna vez has sido infiel?",
  "¿Qué es lo que nunca te has atrevido a preguntarme?",
  "¿Qué harías si un desconocido te besara en la calle?",
  "¿Cuál es el peor error que has cometido?",
  "¿Te alegrarías de ver a alguien a quien odias pasándolo mal?",
  "¿Alguna vez te has vengado de alguien?",
  "Si todas las personas que forman parte de tu vida estuvieran en una casa, esta se incendiara y sólo pudieras salvar a una persona, ¿a quien salvarías?",
  "¿Qué tendría que hacer para seducirte?/ ¿Cómo me seducirías?",
  "¿Qué fue lo primero que pensaste de mí cuando me viste por primera vez?",
  "¿Alguna vez te has enfadado conmigo y no me lo has dicho?",
  "Relata tu experiencia más vergonzosa.",
  "¿Quién te cae mejor de este cuarto?",
  "¿Quién te cae peor de este cuarto?",
  "¿Besarías a alguno de los presentes en este cuarto?",
  "Confiesa la peor mentira que has dicho nunca.",
  "¿A qué edad perdiste la virginidad?",
  "¿Qué cambiarías de tu apariencia física?",
  "¿Recuerdas dónde fue tu primer beso y con quién?",
  "¿Alguna vez te he hecho llorar?",
  "¿Quién crees que es la persona más guapa de esta habitación?",
  "Relata cómo fue la peor cita de tu vida.",
  "¿Cuál es tu mayor deseo?",
  "Di la verdad: ¿te sueles sentir solo/a?",
  "¿Qué es lo mejor de ti?",
  "¿Qué es lo peor de ti?",
  "¿Qué es lo mejor que has hecho en la cama?",
  "¿Con qué famoso te acostarías más de una vez?",
  "¿Con qué amigo en común preferirías acostarte?",
  "¿Has tenido una relación secreta con alguna de las personas que conocemos?",
  "¿Cuándo fue la última vez que te masturbaste?",
  "¿Cuál fue tu peor relación sexual?",
  "¿Quién es más probable que haga un trío primero?",
  "¿Quién es más probable que se case antes?",
  "¿Quién es más probable que se divorcie antes?",
  "¿Quién es más probable que tenga hijos antes?",
  "¿Quién es más probable que deje el trabajo antes?",
  "¿Quién es más probable que se haga rico?",
  "¿Quién es más probable que se haga famosa?",
  "¿Quién es más probable que abandone el grupo de amigxs?",
  "¿Quién es más probable que tenga una aventura con alguien mayor?",
  "¿Quién es más probable que se tire desnudx en una piscina?",
  "¿Quién es más probable que sufra adicción a las drogas?",
  "¿Quién es más probable que sea infiel?",
  "¿Quién es más probable que le salve la vida a alguien?",
  "¿Quién es más probable que atropelle a alguien?",
  "¿Quién es más probable que se acueste con alguien de su mismo sexo?",
  "¿Quién es más probable que se emborrache y caiga en público?",
  "¿Quién es más probable que sobreviva a una apocalipsis zombie?",
  "¿Quién es más probable que vuelva con su ex?",
  "¿Quién es más probable que se ría en el momento inadecuado?",
  "¿Quién es más probable que se duerma en una clase o en el trabajo?",
  "¿Quién es más probable que empiece un rumor?",
  "¿Quién es más probable que se pelee con alguien hasta llegar a las manos?",
  "¿Quién es más probable que tenga un hijo primero?",
  "¿Quién es más probable que le sean infiel?",
  "¿Quién es más probable que se contagie de una enfermedad sexual?",
  "¿Alguna vez lo has hecho en la escuela?",
  "¿Alguna vez lo has hecho en el trabajo?",
  "¿Con cuáles dos personas te gustaría hacer un trío?",
  "Confiesa una cosa extraña que hagas estando solo/a.",
  "¿Te has operado alguna vez?",
  "¿Te operarías por estética?",
  "¿Has pillado a alguien tocándose?",
  "¿Te han pillado a ti tocándose?",
  "¿Alguna vez te ha gustado algún/a profesor/a?",
  "¿Alguna vez te has reído de alguien y te arrepientes?",
  "¿Alguna vez te ha gustado el hermano/a de algún/a amigo/a?",
  "¿Has tenido alguna ETS?",
  "¿Cuál es tu fetiche estrella?",
  "¿Qué es lo más raro que te han pedido hacer en la cama?",
  "¿Alguna vez te has drogado?",
  "¿Alguna vez has sido infiel?",
  "¿Alguna vez te has acostado con el ex o la ex de algún amigo/a?",
  "¿Cuál es tu postura sexual favorita?",
  "¿Alguna vez te has grabado haciéndolo?",
  "¿Has mandado fotos desnudo/a?",
  "¿Alguna vez te han mandado nudes?",
  "Alguna vez has pedido nudes?",
  "¿Cuál es el lugar más extraño en el que te has masturbado?",
  "¿Te gustaría hacer o haces sexo anal?",
  "¿Te has tocado pensando en alguien de esta habitación?",
  "¿Te enrollarías conmigo?",
  "¿Mi novio/a te parece atractivo/a?",
  "¿Alguna vez te ha gustado la pareja de un amigo o amiga?",
  "¿Y la pareja de tu hermano/a?",
  "¿Alguna vez has pillado a tus amigos haciéndolo?",
  "¿Alguna vez te has enamorado de quien no deberías?",
  "¿Alguna vez has mentido al decir te quiero?",
  "¿Alguna vez te has enamorado de tu mejor amigo/a?",
  "¿Alguna vez has dudado sobre tu sexualidad?",
  "¿Alguna vez has hecho tonterías por amor?",
  "¿Alguna vez te has saltado la ley?",
  "¿Serías capaz de perdonar una infidelidad si supieras que esa persona te ama de verdad y solo ha cometido un error?",
  "¿Serías capaz de irte a vivir a otro país ahora mismo por amor?",
  "¿Te gustaría llegar a ser famoso/a?",
  "¿Te gustaría escribir un libro sobre tu vida?",
  "¿Conoces algunos secretos ocultos de tus amigxs?",
  "¿Serías capaz de perdonar la traición de un amigo o amiga?",
  "¿Crees que el tamaño importa?",
  "¿Alguna vez has fingido un orgasmo?",
  "¿Alguna vez te has acostado con alguien y te has arrepentido?",
  "¿Crees que tus amigxs te conocen de verdad?",
  "¿Crees que tu familia te conoce de verdad?",
  "¿Crees que el amor sin sexo es posible?",
  "¿Crees que el amor todo lo puede?",
  "¿Has robado alguna vez?",
  "¿Qué es lo que más te atrae de una mujer físicamente?",
  "¿Qué es lo que más te atrae de la personalidad de una mujer?",
  "¿Qué piensas de tus ex-parejas?",
  "¿De qué encuentro sexual te arrepientes más?",
  "¿Alguna vez has tenido una erección en el momento inadecuado?",
  "¿Alguna vez te has acostado con una amiga o amigo?",
  "¿Te atrae la madre de alguno de tus amigos?",
  "¿Crees que el amor puede durar para siempre?",
  "¿Alguna vez has sido infiel?",
  "¿Cómo te describirías en la cama?",
  "¿Quién es la persona más importante en tu vida?",
  "¿Alguna vez te han roto el corazón?",
  "¿Cómo te consideras en las relaciones?",
  "¿Prefieres dominar en la cama o que te dominen?",
  "¿Alguna vez has mentido al decir que estabas enamorado?",
  "¿Alguna vez te has sentido atraído por la hermana de alguna pareja?",
  "¿Te gustaría tener una orgía?",
  "¿Sueles tener sueños eróticos?",
  "¿Cuál es el sitio más extraño en el que has tenido sexo?",
  "¿Crees que puedes lograr todo lo que te propongas?",
  "¿Con qué hombre tendrías sexo si tuvieras la oportunidad?",
  "¿Te consideras exitoso en la vida?",
  "¿Cuál es la parte de tu cuerpo que menos te gusta?",
  "¿Qué opinas del feminismo?",
  "¿Qué es lo más cruel que le has hecho a alguien?",
  "¿Qué es lo que más te atrae de un hombre?",
  "¿Te llevas bien con tus ex-parejas?",
  "¿Crees en el amor a primera vista?",
  "¿Te gusta algún juego sexual en particular?",
  "¿Qué es lo más loco que has hecho por amor?",
  "¿Qué es lo más atractivo de ti?",
  "¿Cuál de tus amigxs crees que es más atractivo?",
  "¿Te gusta probar cosas nuevas en la cama?",
  "¿Crees que las relaciones a distancia son posibles?",
  "¿Qué tres características debe tener un hombre para conquistarte?",
  "¿Crees que el amor es más importante que la amistad?",
  "¿Tienes algún deseo sexual que nunca hayas confesado?",
  "¿Prefieres dominar en la cama o que te dominen?",
  "¿Te tatuarías el nombre de tu pareja?",
  "¿Harías un striptease?",
  "¿Qué es lo primero que pensaste al verme?",
  "¿Qué saben tus amigxs de mí?",
  "¿Te gusta ver pornografía? ¿De qué tipo?",
  "¿Crees que los demás te tienen envidia?",
  "¿Has tenido fantasías con quien no deberías?",
  "¿Has recibido o recibirías dinero por enviar nudes?",
  "¿Cuál es la peor locura que has hecho por estar enamorada?",
  "¿Cuál es tu mayor arrepentimiento?",
  "¿Has hecho o harías favores sexuales para conseguir lo que quieres?",
  "¿Cuál es tu mayor fantasía sexual?"
]