export const Icebreakers = [
  "¿Cuál es tu bocadillo favorito y dónde lo has comido?",
  "Si solo pudieras comer un alimento el resto de tu vida, ¿cuál sería?",
  "¿Cuál es la receta estrella de tus comidas familiares?",
  "¿Cuál es tu lugar favorito en la tierra?",
  "¿Cuál es el lugar que has visitado y al que no quieres volver?",
  "¿Qué país te llama especialmente la atención?",
  "¿Cuál es para ti el mejor programa de la televisión en este momento?",
  "¿Qué presentador o presentadora te da mala espina?",
  "¿Cuál es la peor película que has visto?",
  "¿Cuál es la última película que has visto en el cine?",
  "¿Cuál es la primera película que recuerdas haber visto en el cine?",
  "¿Cuál crees que es la mejor película de todos los tiempos?",
  "¿Y la mejor serie que has visto nunca?",
  "¿Cuál es el mejor concierto al que has asistido?",
  "¿Cuál es la peor cita que has tenido?",
  "¿Prefieres pasar frío o calor?",
  "¿Cuál es tu canción favorita para darlo todo en el karaoke?",
  "¿Qué libro te marcó en tu infancia?",
  "¿Cuál es la única prenda de vestir sin la que no podrías vivir?",
  "¿Qué prenda no te pondrías nunca?",
  "¿Cuál ha sido la vez te has vestido de una forma más loca?",
  "Si solo pudieras llevar tres cosas a una isla desierta, ¿qué elegirías?",
  "Si pudieras salvar una cosa material de un incendio, ¿qué salvarías?",
  "¿Qué es lo que más te molesta de una persona desconocida?",
  "¿Cuál es tu leyenda urbana favorita que crees que es cierta?",
  "¿Preferirías vivir sin Internet o sin bañarte?",
  "¿Cuál fue la mejor década para la música?",
  "¿Está bien mentir alguna vez?",
  "¿Quién es el famoso más sobrevalorado?",
  "¿Cuál es el peor asiento de un avión?",
  "¿Qué es lo más molesto que hace la gente en público?",
  "¿Están sobrevalorados los aguacates?",
  "¿Quién es tu invitado soñado para una cena, vivo o muerto?",
  "¿Qué harías mañana si ganaras hoy un millón de euros?",
  "¿Es un perrito caliente un sándwich?",
  "¿Te gustan los perros o los gatos y por qué?",
  "¿Estaban Ross y Rachel realmente enamorados?",
  "¿Eres más de vino o de cerveza?",
  "¿Qué te parece que prohíban fumar en las terrazas?",
  "¿Y que las tiendas abran los domingos?",
  "¿Qué te dicen las personas que visten siempre del mismo color?",
  "¿Las películas de superhéroes se están cargando el cine?",
  "¿Crees que un jefe puede ser un amigo de verdad?",
  "¿Es peligroso colgar fotos de las vacaciones con la casa vacía?",
  "¿Qué harías si se fuera la luz en todo el planeta?",
  "¿Los videojuegos son peligrosos para los niños?",
  "¿Quién es la verdadera reina del pop?",
  "¿Son ya las series mejores que las películas?",
  "Tortilla, ¿con o sin cebolla?",
  "¿Había sitio para Jack en la tabla del Titanic?",
  "¿Te comprarías un coche eléctrico?",
  "¿Te has planteado pasarte al veganismo?",
  "¿Cuánto estás dispuesto a pagar por ir a un restaurante Michelin?",
  "¿Teletrabajo o presencialidad?",
  "¿Qué es lo más emocionante de tu trabajo?",
  "¿Qué te gustaría que la gente dijera de ti en tu fiesta de jubilación?",
  "¿Qué es lo más importante que has hecho en el trabajo?",
  "¿Cuál es tu equilibrio ideal entre trabajo y vida privada?",
  "¿Cuál es el mejor consejo profesional que has recibido?",
  "¿Qué es lo que pensabas que era un revés en tu carrera y que en realidad se convirtió en una oportunidad?",
  "¿Cuáles son las cualidades más importantes de un líder?",
  "¿Cómo conseguiste tu primer trabajo?",
  "¿Has hecho algún amigo verdadero en el trabajo?",
  "Si pudieras cambiar de profesión mañana mismo, ¿qué ámbito elegirías?",
  "¿Qué es lo que más valoras en un compañero de trabajo?",
  "¿Qué es lo que menos puedes soportar en un jefe?",
  "¿Qué prefieres, no saber nada o saberlo todo?",
  "¿Qué prefieres, ser eternamente feliz y que nadie más pueda serlo o cederle dicha felicidad a una persona de tu elección (sólo a una) pero tu jamás logres sentir felicidad?",
  "¿Qué prefieres, perder la capacidad de comunicarte con los demás o que todos puedan oír todo lo que piensas?",
  "¿Qué prefieres, vivir en la casa de tus sueños pero en el peor barrio posible (peligroso, alejado y medio abandonado) o en la peor casa del mejor barrio (seguro, prestigioso, bien comunicado y cuidado)?",
  "¿Qué prefieres, ser multimillonario para siempre pero nunca encontrar el amor o encontrar y vivir por siempre con el amor de tu vida pero en las peores condiciones posibles y sin posibilidad de mejora?",
  "¿Qué prefieres, vivir eternamente y ser inmortal o morir en menos de un año sin ningún tipo de dolor y siendo feliz tiempo que te quede?",
  "¿Qué prefieres, ser catapultado y tener que vivir el resto de tu vida en la Edad Antigua (conociendo los acontecimientos históricos que están por venir) o que ocurra lo mismo pero teniendo que vivir en el futuro de dentro de un millar de años?",
  "¿Qué prefieres, hacer lo correcto pero que nadie te lo reconozca y todos te odien por ello o ganar el reconocimiento ajeno haciendo lo contrario a lo que realmente piensas que es correcto?",
  "¿Qué prefieres, ganar el Gordo de Navidad (premio de lotería) o que tu peor enemigo pierda todo su dinero?",
  "¿Qué prefieres, no poder volver a besar a tu pareja o no poder volver a abrazarla?",
  "¿Qué prefieres, olvidar toda tu vida hasta ahora y empezar totalmente de cero (sin recordar ni quien eres, ni las personas que eran importantes para ti, etc.) o no poder nunca introducir ningún cambio en tu vida (permaneciendo todo tal y como está para siempre)?",
  "¿Qué prefieres, comer siempre tu plato favorito o poder variar entre todos los platos que en la actualidad no te gustan?",
  "¿Qué prefieres, que todo el mundo te mire y juzgue cada momento de tu vida o que nadie pueda verte jamás?",
  "¿Qué prefieres, una relación altamente cómplice y comprometida pero en la que jamás haya sexo o una relación basada en el sexo y el placer pero sin que exista nunca complicidad?",
  "¿Qué prefieres, no poder salir nunca de tu casa o no tener jamás un lugar fijo que poder considerar como tal?",
  "¿Qué prefieres, que todo el mundo te considere divertido y se ría con tus comentarios y chistes pero nunca te tomen en serio o que siempre te tomen en serio pero nunca se rían contigo?",
  "¿Qué prefieres, que te quieran pero no te respeten o que te respeten pero no te quieran?",
  "¿Qué prefieres, tener una diarrea permanente o una cefalea continua?",
  "¿Qué prefieres, recibir un millón de euros de golpe o ir recibiendo dos poco a poco a lo largo de los años?",
  "¿Qué prefieres, ver un video en el que tu pareja te es infiel o que tu pareja vea un vídeo en el que tú le eres infiel?",
  "¿Qué prefieres, no volver a sentir tristeza pero jamás volver a sentir alegría o vivir en una oscilación constante entre ambas?",
  "¿Qué prefieres, nacer y vivir para siempre como un niño y nunca crecer o nacer directamente siendo adulto y no haber tenido infancia y vivir siempre como adulto?",
  "¿Qué prefieres, tener una mente de adulto en el cuerpo de un niño o la mente de un niño atrapada en el cuerpo de un adulto?",
  "¿Qué prefieres, saber todo tu porvenir pero no poder modificarlo o evitarlo o no saber nunca lo que está por venir pero tener libertad para elegir?",
  "¿Qué prefieres, que todas las personas de tu entorno te pillen teniendo relaciones sexuales o pillar a cada una de las personas de tu entorno manteniendo sexo?",
  "¿Qué prefieres, que nadie comprenda lo que dices o que tú no puedas comprender a nadie?",
  "¿Qué prefieres, ser capaz de cambiar tu mente y personalidad a voluntad o ser capaz de cambiar tu cuerpo del mismo modo?",
  "¿Qué prefieres, encogerte hasta el tamaño de una pulga o agrandarte hasta el tamaño de un rascacielos?",
  "¿Qué prefieres, que nadie vaya a tu boda o que nadie vaya a tu funeral?",
  "¿Qué prefieres, mentir y que te pillen o pillar a alguien mintiéndote?",
  "¿Qué prefieres, no poder calmar la sed bebas lo que bebas o no poder calmar el hambre comas lo que que comas (sin que por ello murieras ni de sed ni de hambre?",
  "¿Qué prefieres, no tener que volver a dormir o poder dormir en cualquier momento y lugar a capricho (sin que ninguno de los casos tuviera efectos negativos en la salud ni a nivel social)?",
  "¿Qué prefieres, conseguir todos tus sueños sin ningún esfuerzo y sin saber cómo o trabajar duramente para lograrlos (en el supuesto de que pudieran obtenerse en ambos casos)?",
  "¿Qué prefieres: ganar 2 millones de euros hoy mismo, o un sueldo de 10.000€ al mes para toda la vida?",
  "¿Qué prefieres, comprar un piso pequeño en una ciudad que te encante, o una casa grande en un pueblo apartado y que no te llame especialmente la atención?",
  "¿Qué prefieres, no poder volver a comer pizza o no poder volver a beber refrescos?",
  "¿Qué prefieres, no usar nunca más internet o que te amputen un dedo meñique?",
  "¿Qué prefieres, que la vida sea Matrix o que no tenga ningún tipo de sentido?",
  "Si una comida del día tuviera que desaparecer para siempre, ¿preferirías que fuera el desayuno, el almuerzo, la merienda o la cena?",
  "¿Qué prefieres, una vida como la que tienes, o con más hermanos?",
  "¿Qué prefieres, gatos o perros?",
  "¿Qué prefieres, el mar o la montaña?",
  "¿Qué prefieres, tener capacidad absoluta para elegir qué hacer, o tener todas tus necesidades básicas cubiertas?",
  "¿Qué prefieres, tener muchos amigos o tener pocos amigos, pero todos buenos amigos?",
  "¿Qué prefieres, biodiversidad o extracción de recursos naturales?",
  "¿Qué prefieres, decirle a la persona que te gusta que te atrae, o esperar a un momento más propicio?",
  "¿Qué prefieres, hablar de algo de lo que aún no sabes mucho o callar hasta que aprendas mucho más?",
  "¿Qué prefieres, conocer el mundo viajando, o leyendo?",
  "¿Qué prefieres, aceptar el envejecimiento o tratar de maquillarlo?",
  "¿Qué prefieres, productos baratos producidos en masa, o más caros pero locales?",
  "¿Qué prefieres, terminar con la pobreza actual o con la crisis climática?",
  "¿Qué prefieres, poder usar gratis cualquier restaurante del mundo, o poder tener habitaciones gratis en cualquier hotel de tu país?",
  "¿Qué prefieres, ver mejor u oír mejor?",
  "¿Qué prefieres, tener ocho hijos o no tener ninguno?",
  "¿Qué prefieres, no tener nunca pesadillas o poder tener un sueño lúcido cada mes?",
  "¿Qué prefieres, frío o calor?",
  "¿Qué prefieres, trabajar a solas o en grupo?",
  "¿Qué prefieres, terminar con el machismo o con el racismo?",
  "¿Qué prefieres, las películas de terror psicológico o las de terror con monstruos?",
  "¿Qué prefieres, poder volar o poder nadar y bucear sin ahogarte?",
  "¿Qué prefieres, poder ser invisible cuando quieras o tener 5 millones de dólares?",
  "¿Prefieres tener la posibilidad de conocer a tu actor/actriz favorito/a, o conseguir que un personaje de una película de superhéroes lleve tu nombre y apellido?",
  "¿Prefieres dormir perfectamente pero que tu vida sea mediocre, o dormir bastante mal pero que tu vida esté llena de lujos?",
  "¿Qué prefieres, ser el mejor jugador en un equipo de una liga semiprofesional, o ser el peor jugador en un equipo profesional?",
  "¿Qué prefieres, la paz en el mundo o recibir 5 millones de dólares en tu cuenta corriente?",
  "¿Qué prefieres, invertir en inmuebles o en acciones?",
  "¿Qué prefieres, un fin de semana en la playa, o en la nieve?",
  "¿Qué prefieres, tener un coche deportivo muy bonito pero vivir en un apartamento pequeño, o tener un apartamento muy amplio pero conducir un coche utilitario?",
  "¿Qué prefieres, vanilla, chocolate o nata?",
  "¿Qué prefieres, no poder volver a escuchar música jamás, o no poder volver a leer libros?",
  "¿Qué prefieres, que en TV no vuelvan a poner nunca más anuncios, o que nunca más vuelvas a recibir una llamada comercial a tu teléfono?",
  "¿Qué prefieres, que te regalen un apartamento pequeño en Nueva York, o una gran casa con piscina en un pueblo perdido de la zona más deshabitada de tu país?",
  "¿Qué prefieres, vivir intensamente pero durante 50 años, o llegar a los 100 años pero con bastantes enfermedades y achaques?",
  "¿Qué prefieres, un solo amor para toda la vida o varios amores para las diferentes etapas vitales?",
  "¿Cuál es tu superpoder para el día a día?",
  "¿Qué es lo mejor que te ha pasado hoy?",
  "Te levantas un sábado por la mañana sin tener ni una sola tarea pendiente en el horizonte. No tienes problemas de dinero y tienes todo el finde por delante. ¿Qué haces en las próximas 36 horas?",
  "¿Cuál es tu desayuno preferido?",
  "¿Cuándo fue la última vez que viste a un mono?",
  "¿Me recomiendas algún libro reciente que hayas leído?",
  "Si te dieran el dinero necesario para montar un bar o restaurante temático, ¿qué tema elegirías? ¿Cómo llamarías al establecimiento? ¿Y cuál sería el cocktail de la casa?",
  "¿Qué se te da fatal?",
  "¿Qué crees saber más que yo?",
  "¿Qué 3 deseos le pedirías al genio de la lámpara?.",
  "¿Cuál es tu plan ideal para desconectar en vacaciones?",
  "¿Cuál es tu creador de contenido preferido en TikTok? ¿Y en Instagram?",
  "¿Tienes alguna fobia?",
  "¿Cuál es tu juego de mesa preferido?",
  "¿Tenías algún amigo imaginario en tu infancia?",
  "¿Cuál es tu color preferido? ¿Y tienes alguno que odies?",
  "¿Eres más mental o emocional?",
  "¿Cómo es el trabajo de tus sueños?",
  "¿Cuál es la serie de tele que ves cada vez que quieres animarte?",
  "¿Desayunas lo mismo cada día o vas alternando?",
  "¿Cuál es tu estación del año preferida? ¿Por qué?",
  "¿Cuál es tu película preferida de los últimos meses?",
  "¿Y la serie que más has disfrutado?",
  "¿Qué es lo que siempre te hace reír?",
  "¿Eres más de mar o de montaña?",
  "¿Cuál es el viaje más largo que has realizado?",
  "¿Cuál es el emoji que más utilizas en tus chats por WhatsApp?",
  "¿Eres una persona madrugadora o una ave nocturna?",
  "¿Qué museo me recomiendas visitar?",
  "¿Cuáles son tus talentos ocultos?",
  "¿Dónde quieres que quedemos la próxima ocasión?",
  "¿Cuál es la canción que te gustaría cantar en un karaoke a pleno pulmón?",
  "¿A qué país te gustaría viajar la próxima vez?",
  "¿Tenías algún mote divertido en el colegio?",
  "¿Qué hiciste de joven que ahora no te atreverías a hacer ni de coña?",
  "¿Cuál es el libro que más te ha marcado en la vida?",
  "¿Cómo cambiarías la sociedad a mejor?",
  "Si solo pudieras hacer una sola actividad para el resto de tu vida, ¿cuál sería?",
  "Si pudieras viajar hacia atrás en el tiempo para cambiar una sola cosa de tu vida, ¿cuál sería?",
  "¿Qué es para ti la normalidad?",
  "¿Qué te gustaría haber inventado?",
  "¿Te consideras más introvertido o extrovertido?",
  "¿Cuál ha sido la mejor época de tu vida? ¿Y la peor?",
  "¿Cuándo fue la última vez que le rompiste el corazón a alguien?",
  "¿Crees en las segundas oportunidades?",
  "¿Qué historia le contarías a un niño para que se durmiera?",
  "¿Crees que las mentiras, en según que situaciones, se pueden justificar?",
  "¿Alguna vez has sentido simpatía o has estado de acuerdo con un villano de ficción?",
  "¿Qué te gustaría aprender inmediatamente, ahora mismo, si tuvieras la oportunidad?",
  "¿Cuál es tu definición del bien y del mal?",
  "¿Qué pesadillas te han provocado sudores más fríos?",
  "¿Cuál es la injusticia más grave que has sufrido o de la que has sido testigo?",
  "¿Cuál es la persona más agradable que has conocido?",
  "¿Crees en Dios o en alguna fuerza divina?",
  "¿Qué clase de padre o madre te gustaría ser para tus futuros hijos?",
  "¿Qué propósitos del año pasado te han quedado pendientes y te gustaría completar antes de que termine este?",
  "¿Cómo te describirías a ti mismo?",
  "¿Sigues una filosofía de vida?",
  "Si pudieras cambiar el mundo, ¿qué cambiarías?",
  "¿Qué sentido tiene la vida para ti?",
  "Si pudieras acceder a una bola de cristal que sólo predice una cosa sobre tu futuro, ¿Qué te gustaría saber?",
  "¿Qué pregunta quieres que la gente te haga?",
  "Si mañana murieras, ¿qué harías hoy?",
  "¿Cuál es tu mayor logro en la vida?",
  "¿Cuándo fue la última vez que lloraste delante de otra persona?",
  "¿Cuál es la aplicación que más utilizas en tu teléfono?",
  "¿Alguna vez has estado en peligro real?",
  "¿Cocinas a menudo? ¿Qué te gusta cocinar?",
  "¿Qué es la cosa más rara que has comido?",
  "¿Cómo sería para ti el día perfecto?",
  "¿Te gustaría ser famoso o pasar a la historia de alguna forma?",
  "¿Qué es lo que más agradeces de esta vida?",
  "¿Cuál es tu recuerdo de la infancia más preciado?",
  "¿Qué es aquello de lo que jamás harías broma?",
  "¿Qué significa para ti nuestra amistad?",
  "¿Qué aficiones quieres probar?",
  "¿Qué es lo que más te da miedo?",
  "¿Dónde ibas de vacaciones de pequeño?",
  "¿Qué es lo primero que examinas cuando estás buscando nuevo piso o casa?",
  "¿Cuál es tu película preferida? ¿Y la que más odias?",
  "¿Cuál es el acontecimiento más impresionante del que has sido testigo?",
  "¿Cómo fue tu primer día en el cole?",
  "Si pudieras entrevista a alguien, ¿a quién sería?",
  "¿Prefieres ser experto en una sola cosa o ser simplemente bueno en todas?",
  "¿Crees en los aliens?",
  "¿Qué soñaste anoche?",
  "Si solo pudieras comer una sola cosa durante el resto de tu vida, ¿cuál sería?",
  "¿Qué eslogan de anuncio cantaste más veces en la infancia?",
  "¿Cuál es el acontecimiento más afortunado, de pura potra, que has vivido?",
  "¿Cómo fue la peor cita que has vivido?",
  "Si fueras presidente, ¿cuál sería tu plan para mejorar el país?",
  "Si pudieras vivir en otra época, ¿cuál sería?",
  "¿Cuál es tu postre preferido?",
  "¿Cuál es tu plan para sobrevivir durante un apocalipsis zombie?",
  "¿Cómo explicarías la desaparición de los dinosaurios?",
  "¿Qué personaje de Star Wars te gustaría ser?",
  "¿Qué gran invención querrías que existiera antes de morir?",
  "¿Cuándo se puede considerar que alguien ha engañado a su pareja?",
  "¿Qué poder de superhéroe te gustaría tener?",
  "¿Cuál sería la última frase que me dirías antes de revelarme que me has traicionado?",
  "Si existiera la reencarnación, ¿en qué te reencarnarías?",
  "¿Qué cambiarías de ti si pudieras volver a vivir tu vida?",
  "¿Cuál es la película más inapropiada que hayas visto nunca?",
  "¿Formarías parte de los voluntarios que se irían a vivir con los extraterrestres?",
  "¿Qué frase te gustaría que pusiera en tu lápida?",
  "Si pudieras cenar con un personaje histórico, ¿con quién sería?",
  "¿Qué es lo más raro que has querido ser de mayor?",
  "¿Cuál es el sitio más raro en el que te harías un tatuaje?",
  "¿Qué tienes en la nevera ahora mismo?",
  "¿Cómo te gusta ser reconfortado o animado cuando estás triste o enfadado?",
  "¿Dónde te ves en 5 años? ¿Y en 10? ¿Y en 15?",
  "¿Cuál es el momento de tu vida que más te puso a prueba?",
  "¿Te arrepientes de algo? Si es así, ¿de qué?",
  "¿Qué es lo que sueles hacer cuando nadie te mira?",
  "¿Qué crees que nos pasa al morir?",
  "¿Te gustaría tener hijos algún día? ¿Cuántos?",
  "¿Qué es lo primero que recuerdas de tu infancia?",
  "Si tuvieras todo el valor posible para hacer aquello que más te asusta, ¿qué harías?",
  "¿Qué pensamientos te dificultan dormir por las noches?",
  "¿Qué es lo que más te estresa en la vida?",
  "¿Cuál es la peor decisión que has cometido?",
  "¿Cuál fue tu primera amistad? ¿Sigue en tu vida?",
  "¿Cuál fue tu profe preferido de la infancia?",
  "¿Cómo puedo ser un mejor amigo para ti?",
  "¿Cómo se conocieron tus padres?",
  "Si pudieras cambiar una sola cosa sobre ti, ¿cuál sería?",
  "De todos los miembros de tu familia, ¿con quién te llevas mejor?",
  "¿Crees en fantasmas o en el más allá?",
  "¿Cuál es tu comida basura preferida?",
  "¿Qué es lo que más te gusta hacer en tu tiempo libre?",
  "¿Cuál es tu recuerdo favorito de todos los tiempos?",
  "¿Qué es lo que más te hace llorar?",
  "Si te tocara la lotería, ¿qué harías con ese dinero?",
  "Si tuvieras la oportunidad de ser inmortal, ¿cómo la aprovecharías?",
  "¿Tienes alguna manía extraña que no conozco?",
  "¿Cómo sería para ti la cita ideal?",
  "¿Cuál es tu signo del zodiaco?",
  "¿Cuál es tu afición preferida?",
  "¿Te gusta algún famoso o famosa? ¿Qué es lo que te gusta de él o de ella?",
  "¿Qué es lo que más te gusta de tu trabajo?",
  "¿Qué fue lo primero que pensaste de mí nada más conocernos?",
  "¿Cuál es tu palabra preferida?",
  "¿Cuál es el mejor regalo que te han hecho? ¿Quién te lo dio?",
  "¿Alguna vez has estado en una relación sería?",
  "¿Qué es la cosa más espontánea que has llegado a hacer?",
  "¿Qué es lo que realmente te saca de tus casillas?",
  "¿Cuántos años tenías cuando diste el primer beso? ¿Cómo fue?",
  "¿A quién más admiras en este mundo?",
  "¿Qué país me recomendarías para viajar?",
  "¿Si pudieras volver a empezar tu vida en cualquier rincón del mundo, cuál elegirías?",
  "¿Qué es lo que te motiva al levantarte cada mañana?",
  "¿Cuáles son las 3 cosas que más te molestan?",
  "¿Cuál es tu plan de fin de semana ideal?",
  "¿Te resulta fácil confiar en alguien?",
  "¿Qué pedirías si fueran a concederte un solo deseo?",
  "¿Podrías perdonar a alguien que te ha sido infiel si te enteraras que de todas maneras te ama?",
  "¿Cuándo es tu cumpleaños?",
  "¿Qué ha sido lo mejor que te ha pasado en la vida?",
  "¿Qué persona ha ejercido una influencia decisiva en ti?",
  "¿Cuál es la mayor locura que has hecho por amor?",
  "¿Qué es lo que más te gusta de mí?",
  "¿Cuál es la parte de mi cuerpo que más te gusta?",
  "¿Qué color crees que me queda mejor?",
  "¿Sueñas a menudo? ¿Con qué sueñas?",
  "¿Te gusta lo que llevo hoy?",
  "¿Cómo sería para ti la relación ideal?",
  "¿Qué pasaría si me enamorara de ti?",
  "¿Cuál es tu mejor frase para ligar?",
  "¿Tienes alguna fantasía secreta?",
  "¿Crees en las parejas perfectas?",
  "¿Cuál crees que es mi comida preferida?",
  "¿Si ahora mismo saliéramos de cita, a dónde me llevarías?",
  "¿Qué es lo que más te ha gustado de lo que hemos hecho hoy?",
  "Si fuera una flor, ¿cuál crees que sería?",
  "¿Cuál era tu amor secreto de juventud?",
  "¿Qué es aquello que me hace diferente del resto de personas?",
  "¿A qué actor o actriz crees que me parezco?",
  "¿Cuándo fue la última vez que te pusiste triste?",
  "¿Crees en el destino?",
  "¿Te gustan las películas románticas? ¿Cuál es tu preferida?",
  "¿Tienes alguna fantasía íntima?",
  "¿Qué es lo que más valoras en una pareja?",
  "¿Cuántos hijos quieres tener?",
  "Si lograra sentir algo que tú sientes, ¿qué elegirías?",
  "¿Cómo sería tu noche perfecta?",
  "¿Qué parte del cuerpo te parece más erótica?",
  "¿Si pudieras tener un dinosaurio de mascota, cuál sería?",
  "¿Cuál es el meme que más te ha hecho reír últimamente?",
  "¿Qué canción te sabes de memoria y te da vergüenza?",
  "¿Si fueras un sabor de helado, cuál serías y por qué?"
]
