export const Intimacy = [
  "¿Quién es la persona más importante en tu vida y por qué?",
  "¿Quién es la persona que más te hace sentir como en casa?",
  "¿Tienes un mentor?",
  "¿Has roto alguna vez con un amigo y por qué?",
  "¿Cuántos amigos íntimos es lo ideal?",
  "¿Crees en las almas gemelas?",
  "¿Cuál es el mejor consejo que te ha dado tu padre o tu madre?",
  "¿Qué es lo que te ponía más nervioso de tus hermanos cuando eras pequeño?",
  "¿Tus abuelos te contaban historias de su juventud?",
  "¿Tienes el típico tío que siempre la caga en las reuniones familiares?",
  "¿Cuál es el mejor cumplido que has recibido?",
  "¿Qué quieres que la gente diga de ti en tu funeral?",
  "¿Te imaginas que nos caemos bien?",
  "¿Te consideras una persona muy directa?",
  "¿Cómo ha sido la cita más absurda que has tenido por redes?",
  "¿Qué odias más en este instante con todas tus fuerzas?",
  "¿Alguna vez has insultado a algún famoso por Instagram?",
  "¿En qué concierto te gustaría estar ahora mismo?",
  "¿Estás planeando algún viaje?",
  "¿Qué plan te gustaría más para tu despedida antes de la boda?",
  "Si tuviéramos un gato, un perro y un canario, ¿qué nombre le pondrías a cada uno?",
  "¿Cuál ha sido el momento más vergonzoso de tu vida?",
  "Muestra una foto de tu primera comunión (o de la infancía)",
  "¿Cuándo fue la última vez que sentiste placer verdadero?",
  "¿Te planteas mucho el tema de la monogamia o la apertura de la pareja?",
  "Cuando sientes celos, ¿te cabreas más con la otra persona o contigo?",
  "¿Te plantearías vivir en otro país si te sale una oportunidad de trabajo?",
  "¿Algún ex es o podría llegar a ser una gran amistad?",
  "¿Has ido alguna vez a terapia? ¿Te gustaría?",
  "¿Has descubierto en ti algún patrón de comportamiento de tus padres que te preocupe?",
  "¿Te irías de vacaciones solo con amigos y sin tu pareja?",
  "¿Qué crees que pensaría tu familia de mí?",
  "¿Qué consejo le darías a tu yo de 10 años?",
  "¿Y qué crees que te diría tu yo de 10 años sobre tu vida actual?",
  "Visualízanos juntos dentro de 10 años: ¿qué ves?",
  "¿Quién eres?",
  "¿Qué es lo te hace sentir vivo?",
  "¿Cuál es tu mayor miedo?",
  "¿Qué cambiarías de tí mismo?",
  "¿Cuál es tu mayor sueño?",
  "¿Alguna vez has sido cruel o has utilizado a alguien?",
  "¿Tienes algún vicio inconfesable?",
  "¿Cuando mentiste por última vez en algo importante?",
  "¿Qué es lo más vergonzoso que alguien te ha pillado haciendo?",
  "¿Qué piensas de ti mismo como persona?",
  "¿Tienes algún complejo? ¿Cuál?",
  "¿A quién de los otros candidatos no cogería y por qué?",
  "¿Cuál es la parte de tu cuerpo que más te gusta?",
  "¿Y del mío?",
  "¿De qué te arrepientes más?",
  "¿Hasta donde llegarías por cumplir un antojo?",
  "¿Qué es lo más loco que has hecho por amor?",
  "¿Prefieres ser el autor de una injusticia o su víctima?",
  "¿Te has rendido en algo en la vida?",
  "¿Alguna vez has sido infiel?",
  "¿Qué es lo que nunca te has atrevido a preguntarme?",
  "¿Qué harías si un desconocido te besara en la calle?",
  "¿Cuál es el peor error que has cometido?",
  "¿Te alegrarías de ver a alguien a quien odias pasándolo mal?",
  "¿Alguna vez te has vengado de alguien?",
  "Si todas las personas que forman parte de tu vida estuvieran en una casa, esta se incendiara y sólo pudieras salvar a una persona, ¿a quien salvarías?",
  "¿Qué tendría que hacer para seducirte?/ ¿Cómo me seducirías?",
  "¿Con qué personaje histórico te identificas?",
  "¿Cuál es el trabajo de tus sueños?",
  "¿Cuál es el estado de ánimo más desagradable para ti?",
  "¿Tienes algún libro favorito? ¿Cuál es?",
  "¿Escondes algún secreto?",
  "¿Sientes miedo por algo?",
  "¿Qué es lo que más valoras de nuestra amistad?",
  "Dime tres bandas musicales que te hayan marcado",
  "¿Qué significado tiene para ti la libertad?",
  "¿Cuál es el recuerdo más vergonzoso de tu infancia?",
  "¿Piensas con frecuencia en cómo te sientes?",
  "¿Dónde te irías de vacaciones?",
  "Dime las cuatro series que más te gusten",
  "¿Qué cualidades valoras más en alguien?",
  "Si pudieras, ¿qué harías para cambiarlo?",
  "¿Qué clase de personas son las que te dan más lástima?",
  "¿Cómo me describirías?",
  "Si fueses un animal… ¿cuál serías?",
  "¿Tienes un sitio preferido para vivir?",
  "¿Qué es lo que más te gusta sobre tu persona?",
  "¿Qué música escuchas?",
  "¿Qué cuatro adjetivos te definen?",
  "¿Qué es lo que más deseas en esta vida?",
  "¿Cuál ha sido tu mejor momento de tu vida?",
  "¿Dónde te irías conmigo a pasar unos días?",
  "¿Qué te gustaría lograr en esta vida?",
  "¿Quién es la persona más importante de tu vida?",
  "¿Qué es lo que más te atrae del sexo opuesto (o del mismo sexo en el caso de los homosexuales)?",
  "¿Hay algo que desees hacer en tu vida más que nada?",
  "¿Perdonarías una infidelidad?",
  "¿Cuál es tu película favorita? ¿Por qué?",
  "¿Mar o montaña?",
  "Cuando eras pequeño, ¿qué querías ser de mayor?",
  "¿Cuál es tu mayor virtud y tu mayor defecto?",
  "¿Qué talento desearía tener?",
  "¿En qué situaciones estarías dispuesto o dispuesta a mentir?",
  "¿Qué tipo de personas son más atractivas para ti?",
  "¿De qué estás más orgulloso en esta vida?",
  "Y… ¿de lo que más te arrepientes?",
  "¿Qué es para ti la infidelidad?",
  "¿Perdonarías a alguien que te hizo bullying?",
  "¿Buscas el amor o dejas que este venga solo?",
  "¿Cuál es tu habilidad más especial?",
  "¿En qué país te gustaría vivir?",
  "¿Eres más de gatos o de perros?",
  "¿Qué es para ti la felicidad?",
  "¿Te irías a vivir al extranjero por amor?",
  "¿Te acuerdas del día en que nos conocimos?",
  "¿Qué fue lo primero que pensaste de mí tras conocerme por primera vez?",
  "¿Cuál ha sido el mayor sacrificio que has hecho por amor?",
  "¿Qué superpoder te gustaría tener?",
  "¿Cuál crees que es mi mayor virtud?",
  "¿Cuál crees que es mi mayor defecto?",
  "¿Te han rechazado alguna vez?",
  "¿Cómo sería tu pareja ideal?",
  "¿Tuviste una infancia feliz?",
  "¿Cuál sería tu viaje ideal?",
  "¿Has tenido alguna relación poliamorosa o abierta?",
  "¿Qué aprendiste de tus padres?",
  "¿Tienes buena relación con tus padres?",
  "¿Si gobernaras tu país qué es lo primero que harías?",
  "¿Cuándo lloraste por última vez?",
  "¿Qué opinas del feminismo?",
  "¿Cual es el mayor problema social de tu país actualmente?",
  "¿Si pudieras viajar en el tiempo dónde irías?",
  "¿Qué crees que opinaría de ti tu yo de 10 años?",
  "¿Cuál fue el día más feliz de tu vida?",
  "¿Te gusta ir a conciertos o festivales de música?",
  "¿Te gusta practicar deportes extremos?",
  "¿Cuál es tu equipo favorito?",
  "¿Te has convertido en la persona que querías ser?",
  "¿Te gusta practicar yoga?",
  "¿Qué opinas sobre la muerte?",
  "¿Cuál es tu signo del zodíaco?",
  "¿Te gusta meditar?",
  "¿Tienes algún miedo que no le hayas contado a nadie?",
  "¿Cuál ha sido tu experiencia más vergonzosa?",
  "¿Qué cualidades crees que tienes?",
  "¿Cuáles son tus peores defectos?",
  "¿Te consideras una persona feliz?",
  "Si pudieras borrar alguna experiencia negativa de tu vida, ¿cuál sería?",
  "¿Qué cambiarías de tu vida si pudieras?",
  "¿Has sido cruel con alguien en alguna ocasión?",
  "¿Qué es lo más extravagante que has hecho?",
  "¿Has robado algo alguna vez?",
  "¿Qué es lo que te produce más asco?",
  "¿Cuándo fuiste grosero por última vez y por qué?",
  "¿Tienes algún problema de inseguridad?",
  "¿Qué parte no te gusta de tu aspecto físico?",
  "¿Cuál ha sido tu mayor fracaso?",
  "¿Cuál es la mentira más grande que has contado?",
  "¿Cuál ha sido la vez que más has hecho el ridículo?",
  "¿En qué cosas crees que te admiran los demás?",
  "¿Qué es lo peor que has hecho estando borracho?",
  "¿Has hecho algo ilegal en lo que llevamos del año?",
  "¿Qué actitudes te ofenden de los demás, pero no lo dices?",
  "¿Has traicionado a alguien alguna vez?",
  "¿A quién extrañas de tu pasado?",
  "¿Qué opinas del feminismo?",
  "¿Qué es lo más raro que sueles hacer cuando estás solo?",
  "¿En qué área te consideras sin habilidades?",
  "Según tú, ¿qué es lo que te falta por experimentar?",
  "¿Cuándo sentiste envidia por última vez y por qué?",
  "¿Cómo te ves dentro de 10 años?",
  "¿Te gusta tu trabajo?",
  "¿Tienes algún tipo de deuda que saldar (personal, emocional, económica)?",
  "¿Te consideras una persona espiritual?",
  "¿Te consideras una persona libre o hay algo que te limita o condiciona?",
  "¿Acogerías en tu casa a algún emigrante o refugiado de otro país?",
  "¿Crees en la venganza?",
  "Si tu vida fuera un libro, ¿qué título llevaría?",
  "¿Qué hay más allá de la muerte según tú?",
  "¿Cómo te gustaría que fuera tu funeral?",
  "¿Crees que estamos solos en el universo?",
  "¿Crees que los demás piensan que eres aburrido?",
  "¿Cuál es tu manía más rara?",
  "¿Cuál es tu melodía favorita para cantar en la ducha?",
  "¿Una película mala que te guste?",
  "¿Qué es lo más extraño que has buscado en Google?",
  "¿En qué piensas cuando estás en el baño?",
  "¿Duermes con la boca abierta?",
  "Si estuvieras en el club de la pelea, ¿con quién te liarías a golpes?",
  "¿Cuál es el sitio más extraño que has tenido que usar como baño?",
  "¿Cuánto tiempo has pasado sin bañarte?",
  "¿Tuviste piojos cuando estabas en la escuela?",
  "¿Te has puesto ropa interior que tenga agujeros?",
  "¿Qué es lo más extraño que te has comido?",
  "¿Algo que huele mal pero que aún así te agrada?",
  "¿Te has enamorado de varias personas al mismo tiempo?",
  "¿Te parece atractivo alguien de tu mismo sexo?",
  "¿Algo que nunca fallaría para seducirte?",
  "¿Hay algo en lo que le dirías que no al amor de tu vida, aunque te lo pidiera de rodillas?",
  "Si estuviera permitida la poligamia, ¿quién sería tu segunda pareja?",
  "Si fueras a un sitio de intercambios, ¿con quién permitirías que estuviera tu pareja?",
  "¿Cuál es la pareja que más te ha hecho llorar?",
  "¿Y a quién hiciste llorar tú?",
  "¿Alguna vez te juntaste con alguien por conveniencia?",
  "¿Qué es lo peor que has hecho por amor?",
  "¿Cuál es el mayor rechazo que has tenido en el amor?",
  "¿Tendrías una relación abierta?",
  "¿Le has roto el corazón a alguien alguna vez?",
  "¿Has dicho alguna vez «te quiero» sin sentirlo realmente?",
  "¿Te han dejado plantado alguna vez?",
  "¿Has sido infiel alguna vez?",
  "¿Alguna vez has estado con alguien para olvidar a otra persona?",
  "¿Tienes algún pretendiente ahora mismo?",
  "¿Sueles abordar a las personas que te gustan, o te vence la timidez?",
  "¿Cuánto tiempo duró la relación amorosa más breve que has tenido?",
  "¿Has pensado alguna vez en tener algo con la madre de un amigo?",
  "¿Qué es lo que no toleras en una relación de pareja?",
  "¿Tendrías una relación con alguien de tu mismo sexo?",
  "¿Te has enamorado alguna vez de la pareja de un amigo?",
  "¿Con qué actor o actriz te gustaría pasar una noche?",
  "¿Te tatuarías el nombre de tu pareja?",
  "¿Qué es lo primero en que te fijas cuando tienes una cita con alguien?",
  "¿Qué línea jamás cruzarías para conquistar a alguien?",
  "¿Das importancia al dinero de tus potenciales parejas?",
  "¿Cuál es el regalo más incómodo que te ha dado una ex pareja?",
  "¿Qué te daba vergüenza de tu ex y nunca le dijiste?",
  "¿Alguna vez has consumido drogas solo para intentar ligar con alguien?",
  "¿Cambiarías a tu pareja por un millón de euros?",
  "¿Cuál ha sido tu peor cita?",
  "Si embarazaras a alguien de improviso y no te consideras listo para ser padre, ¿qué harías?",
  "¿Sueles coquetear aún si tienes pareja?",
  "¿Quién es la persona que más te arrepientes de haber besado?",
  "¿Qué harías si descubres a tu pareja siéndote infiel?",
  "¿Te observas?",
  "¿Alguna vez te has casado o has pensado en casarte en un momento de locura?",
  "¿Qué es lo más vergonzoso que has hecho frente a alguien que te gusta?",
  "Si tu cita fuera un desastre, ¿cómo escaparías de ella?",
  "¿Te le has declarado a alguien que no te correspondió?",
  "¿Alguna vez te ha atraído alguien mucho mayor que tú?",
  "¿Alguna vez enamoraste a una persona y después te arrepentiste?",
  "¿Qué característica física te haría no tener una cita con una persona?",
  "¿Se te ha pasado por la cabeza volver con tu ex?",
  "¿Consideras que las relaciones deben de ser lindas y románticas o intensas y apasionadas?",
  "¿Has besado alguien con mal aliento?",
  "¿Quién es el amor platónico que te da más vergüenza reconocer?",
  "¿Qué haces si descubres que no tienes dinero para pagar en una cita?",
  "¿Alguna vez te escapaste del colegio para ver a tu novio o novia?",
  "¿Le suplicarías a alguien por amor?",
  "¿Alguna vez te enamoraste de un profesor?",
  "¿Aún tienes contacto con tu primer amor?",
  "¿Cuándo crees que una persona está lista para el matrimonio?",
  "¿Has fingido estar enfermo para no salir con alguien?",
  "¿Cómo arruinar una cita con tres palabras?",
  "¿Cuál ha sido tu peor ataque de celos?",
  "¿Cuál es la parte del cuerpo que más miras en una persona?",
  "¿Has tenido fantasías con personajes animados?",
  "¿Qué te gusta que te digan cuando haces el amor?",
  "¿Gritas, gimes, susurras o lo haces en silencio?",
  "Para un trío, ¿escogerías a alguien de tu mismo sexo o del sexo opuesto?",
  "¿Te gustan los juegos previos o prefieres ir directo al grano?",
  "¿Has tenido pensamientos raros mientras haces el amor?",
  "¿Qué grado de importancia tiene la intimidad en una relación sentimental para ti?",
  "¿Has podido satisfacer tu fantasía sexual más bizarra? ¿Cuál era?",
  "¿Tienes fetiches sexuales?",
  "¿Con cuántas personas te has acostado?",
  "¿Cuál es tu límite en las relaciones íntimas?",
  "¿Qué es lo que más te excita?",
  "¿Has utilizado algún objeto como juguete sexual?",
  "¿Has hecho el amor en algún lugar prohibido?",
  "¿Has tenido un encuentro íntimo con alguien a a quien hayas conocido ese mismo día?",
  "¿Harías un striptease?",
  "¿Te gustaría probar el BDSM?",
  "¿Te has arrepentido de acostarte con alguien?",
  "¿Has encontrado a alguien manteniendo relaciones sexuales?",
  "¿Cuáles son los tres adjetivos te describen mejor en la cama?",
  "¿Alguna vez has tenido sexo en un lugar de trabajo?",
  "¿Has tenido alguna ETS?",
  "¿Te gusta tomar o que tomen la iniciativa en la cama?",
  "¿Cuándo fue la primera vez que te sentiste excitado y cómo fue?",
  "¿Ves contenido para adultos regularmente?",
  "¿Alguna vez has visto a alguien desnudo por accidente?",
  "¿Cuál es para ti la diferencia entre tener sexo y hacer el amor?",
  "¿Cuál es el lugar más incómodo en el que lo has hecho?",
  "¿Alguna vez has fingido un orgasmo?",
  "¿Tienes alguna foto comprometedora que preferirías eliminar de la faz de la tierra?",
  "¿Has pensado en hacer un trío?",
  "¿Cuál es la relación sexual más larga que has tenido?",
  "¿Qué es lo más vergonzoso que te ha pasado mientras tenías sexo?",
  "¿Piensas en tu ex estando con tu pareja?",
  "¿En qué tres lugares te encantaría tener sexo?",
  "¿Qué te gusta más: que te dominen o dominar?",
  "¿Tienes algún deseo que pudiera parecer vergonzoso?",
  "¿Te has acostado con una persona sin ni siquiera saber su nombre?",
  "¿Has viajado a otra ciudad para tener sexo con alguien?",
  "¿Cada cuánto te masturbas?",
  "¿Cuál es tu posición sexual favorita?",
  "¿Cuál ha sido el elogio más grande que alguien ha dicho de tu cuerpo desnudo?",
  "¿Te has acostado con más de una persona el mismo día?",
  "¿Te gusta ambientar con música mientras tienes intimidad?",
  "¿A quién odiarías ver desnudo?",
  "¿Eres voyerista?",
  "¿Hay alguna escena de alguna película que te excite?",
  "¿Cuál es tu fetiche más extraño?",
  "¿Cuál fue el último sueño erótico que tuviste?",
  "¿Has enviado nudes?",
  "¿Tenías un amigo imaginario en tu infancia? ¿Cómo se llamaba?",
  "¿Qué sería lo último que le dirías a tu mejor amigo si sabes que va a morir?",
  "¿Te has molestado con un amigo hasta el punto de no volver jamás a hablarle?",
  "¿Te has enamorado de un familiar?",
  "¿A quién quieres más: a tu padre o a tu madre?",
  "¿Has hablado mal de un amigo cercano?",
  "¿Alguna vez has discutido con la pareja de un amigo?",
  "¿Quién es la persona que más necesitas en tu vida ahora mismo?",
  "Si supieras que el novio de tu amiga la engaña, ¿qué harías?",
  "¿Alguna vez has coqueteado con los hermanos de tu mejor amigo?",
  "¿Qué es lo más embarazoso que tus padres te han pillado haciendo?",
  "¿Qué serías capaz de hacer por tu familia?",
  "¿Hay algo que no puedes perdonarles a tus padres?",
  "¿Has revisado el teléfono móvil de tus amigos sin su permiso?",
  "¿Crees que hombres y mujeres pueden ser amigos (y solo amigos)?",
  "Del 1 al 10, ¿cómo calificas tu físico, tu personalidad y tu intelecto?",
  "Cuando hablas contigo, ¿de qué hablas?",
  "¿Qué debería decir en tu tumba?",
  "¿Cuál fue tu experiencia más vergonzosa de la secundaria?",
  "¿Qué es lo primero que harías si fueras invisible?",
  "¿Crees que se deberían repartir por igual todas las riquezas del mundo?",
  "Si se abolieran todas las leyes, ¿cuál sería tu primer delito?",
  "¿A cuál lugar no volverías jamás, ni por todo el dinero del mundo?",
  "Si pudieras hacer desaparecer a alguien, sin que quedara ningún rastro, ¿quién sería?",
  "Si reencarnaras en un personaje de ficción, ¿cuál te gustaría?",
  "¿Alguna vez te han cacheteado?",
  "¿Qué te llevarías a una isla desierta?",
  "Si ves una pelea en la calle, ¿intentas mediar o pasas de largo?",
  "¿Alguna vez has fingido que te gusta un regalo?",
  "¿Alguna vez has practicado besarte en un espejo?",
  "¿Qué harías si estuvieras en el baño y no quedara papel higiénico?",
  "¿Qué es lo primero que harías si te despertaras siendo alguien del sexo opuesto?",
  "¿Te sientes solo?",
  "¿Alguna vez te han pillado haciendo algo que no deberías?",
  "¿Has conocido alguna vez a alguien a quien le perdonarías todos los fallos?",
  "¿Qué serías capaz de hacer por tener la vida económicamente resuelta?",
  "¿Te gustaría operarte alguna parte de tu cuerpo?",
  "¿Qué opinas de la depilación genital?",
  "¿Crees que hay que ser buena persona por encima de todas las cosas?",
  "¿Has pensado alguna vez que te gustaría matar a alguien?",
  "Si solo pudieras hacer alguna de las dos, ¿viajarías al futuro o al pasado?",
  "¿Te han expulsado de una discoteca alguna vez?",
  "¿Piensas que las personas te tienen envidia?",
  "¿Te han detenido en alguna ocasión?",
  "¿Cuál es el castigo más ridículo que te ha tocado hacer en un juego?",
  "¿Sientes temor a la vejez?",
  "¿Qué te hace sentir vulnerable?",
  "¿Has padecido algún tipo de discriminación?",
  "¿Qué metas tienes en la vida que no has podido cumplir aún?",
  "¿Has tenido experiencias paranormales?",
  "¿Qué cosa infantil crees que sigues haciendo?",
  "¿Espiarías a alguna persona si tuvieras poderes especiales?",
  "¿Qué personaje famoso finges que no te gusta, pero en realidad sí?",
  "¿Cuál es tu mal hábito más raro?",
  "En un incendio, ¿salvarías tus ahorros de toda la vida o a tu mascota?",
  "¿Crees que eres una persona inteligente?",
  "¿Qué placer te hace sentir culpable?",
  "¿Qué cosas quieres lograr antes de morir?",
  "¿Tus padres han influido en los objetivos que tienes?",
  "¿Cuál es la cosa más loca y ambiciosa que quieres lograr?",
  "¿Qué esperas lograr en tu vida profesional?",
  "¿Cuál crees que es la mejor manera de mantener tus pasiones motivadas y cumplir tus metas?",
  "Si pudieras hacer algo por el resto de tu vida, ¿qué sería?",
  "¿Qué te gustaría que las personas sientan cuando están a tu alrededor?",
  "¿Tienes más miedo a la muerte o a no sentirte realmente vivo?",
  "¿Estás orgulloso de lo que estás haciendo con tu tiempo en este momento?",
  "¿Alguna vez algo o alguien te ha salvado la vida?",
  "¿Hay algo por lo que desearías haber pedido perdón, pero nunca lo hiciste?",
  "¿Cuáles son las cosas que quieres que la gente sepa de ti?",
  "¿Te consideras una persona polémica? ¿Por qué?",
  "¿Qué idea equivocada se suele formar la gente de ti?",
  "¿Cuál es la cosa más loca que has hecho alguna vez y qué harías de nuevo?",
  "¿Te consideras inferior o superior a la mayoría de las personas?",
  "¿Alguna vez te has reído en el momento más inoportuno?",
  "¿Has salido alguna vez a la calle sin ropa interior?",
  "¿Te depilas las zonas íntimas?",
  "¿Cuánto ha sido el máximo de tiempo que has pasado sin ducharte?",
  "¿Tienes una corazonada secreta sobre cómo morirás?",
  "¿Cuál es el apodo más vergonzoso que te han puesto?",
  "¿Qué cosas te interesan que a la mayoría de la gente no le importen?",
  "¿Qué canción serviría para resumir tu personalidad? ¿Por qué?",
  "¿De qué manera prefieres relacionarte con las personas?",
  "¿Con qué tipo de personas jamás te llevarías bien?",
  "¿Crees que te tomas las cosas demasiado personal?",
  "¿Alguna vez hiciste algo que intencionalmente afectaría a otra persona?",
  "Si no trabajaras en lo que trabajas actualmente, ¿a qué te hubieras dedicado?",
  "Si pudieras desaparecer y comenzar una nueva vida desde cero, ¿lo harías?",
  "¿A qué persona prefieres pedir consejos?",
  "Si supieras que vas a morir en un año, ¿qué harías?",
  "Si se pudiera, ¿te gustaría vivir para siempre?",
  "¿Qué consejo le darías al niño que fuiste?",
  "¿Aún tienes contacto con tu primer amor?",
  "¿Cuándo fue la última vez que sentiste que tuviste una nueva oportunidad?",
  "¿Eres una persona con convicciones políticas o eres de los que no va a votar?",
  "¿Amas más a tu mascota que a algunas personas de tu entorno?",
  "¿Cuál fue la locura de tu adolescencia que nunca le contaste a tus padres?",
  "¿Hay algo que no puedes perdonarles a tus padres?",
  "¿Serías capaz de estar una semana sin internet y sin tu teléfono móvil?",
  "Si volvieses a nacer, ¿repetirás tu vida de la misma manera?",
  "¿En qué situación temiste más por tu vida?",
  "¿Qué le dirías a Dios para convencerlo de que te mereces estar en el cielo?",
  "¿Qué pregunta desearías que no te hicieran nunca?",
  "¿Te vistes bien o te da igual?",
  "¿Qué haces cuando vas por la calle y ves a una persona que conoces pero que no te agrada?",
  "¿Te llevas bien con todas o todos tus ex?",
  "¿Quién crees que merece la pena de muerte?",
  "Si detectas que una persona te está mintiendo, ¿qué haces?",
  "Si solo existieran dos opciones, ¿qué prefieres: feliz y pobre o triste y rico?",
  "¿Crees que el futuro será mejor o peor de lo que es ahora?",
  "¿Imágenes o palabras?",
  "¿Cosas no sexuales que te excitan?",
  "¿Cómo le pides a alguien que se calle, de manera amable?",
  "¿Abrirías la caja?",
  "¿Cuál es la razón más tonta por la que has terminado una relación?",
  "¿Cómo se llamaba tu amigo imaginario de la infancia?",
  "¿Qué delito cometerías?",
  "¿Matarías a alguien?",
  "¿Borrarías tus recuerdos?",
  "¿Eres egoísta?",
  "¿Revelarías el desenlace?",
  "¿De qué hablas con tu mascota?",
  "¿Lo más estúpido que has dicho?",
  "¿Te crees especial?",
  "¿Lo has hecho en la parte de atrás del coche?",
  "¿Qué le falta a tu vida sexual?",
  "¿A quién salvarías?",
  "¿El peor chiste que has contado?",
  "¿Reír solo o acompañado?",
  "¿Estás subvalorado/a o sobrevalorado/a?",
  "¿Sabes cuál es tu mayor habilidad?",
  "¿Te has ido sin pagar la cuenta?",
  "¿Más amores u odios?",
  "¿De qué te arrepientes?",
  "¿Cómo es tu mirada?",
  "¿Visible o invisible?",
  "¿Cuál instrumento eres?",
  "¿Interrogar o ser interrogado?"
]